Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-09, with the labels that each got.

#357 chore(PPDSC-2379): update k8 ingress
  eks/manifests/ingress.yaml
Labels: ready for review

#356 docs(PPDSC-2336): chore-ppdse-2336-added NextLink added to site
  .eslintrc.js
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/menu-collapsible/menu-collapsible.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/sidebar-navigation.tsx
  site/components/site-header.tsx
Labels: docs, ready for review

#361 build(PPDSC-2404): add version back into image name for dev deploy
  .circleci/config.yml
Labels: ready for review

#358 docs(PPDSC-2288): Flag documentation
  site/components/illustrations/components/flag-illustration.tsx
  site/components/illustrations/components/flag/anatomy.tsx
  site/components/illustrations/components/flag/options/appearance.tsx
  site/components/illustrations/components/flag/options/icons.tsx
  site/components/illustrations/components/flag/options/size.tsx
  site/components/illustrations/components/flag/usage/do-01.tsx
  site/components/illustrations/components/flag/usage/do-02.tsx
  site/components/illustrations/components/flag/usage/dont-01.tsx
  site/pages/components/flag.mdx
  site/pages/components/flag.tsx
  site/routes.ts
Labels: docs, ready for review

#353 docs(PPDSC-2290): Audio player documentation
  site/components/illustrations/components/audio-player-illustration.tsx
  site/components/illustrations/components/audio-player/anatomy/anatomy-01.tsx
  site/components/illustrations/components/audio-player/anatomy/anatomy-02.tsx
  site/components/illustrations/components/audio-player/anatomy/anatomy-03.tsx
  site/components/illustrations/components/audio-player/behaviours/buffering.tsx
  site/components/illustrations/components/audio-player/behaviours/mute-button.tsx
  site/components/illustrations/components/audio-player/behaviours/play-pause-live.tsx
  site/components/illustrations/components/audio-player/behaviours/play-pause-recorded.tsx
  site/components/illustrations/components/audio-player/behaviours/skip-next.tsx
  site/components/illustrations/components/audio-player/behaviours/skip-previous.tsx
  site/components/illustrations/components/audio-player/layout-examples/full-player.tsx
  site/components/illustrations/components/audio-player/layout-examples/inline-player.tsx
  site/components/illustrations/components/audio-player/layout-examples/player-in-card.tsx
  site/components/illustrations/components/audio-player/options/autoplay.tsx
  site/components/illustrations/components/audio-player/options/forward-replay.tsx
  site/components/illustrations/components/audio-player/options/live.tsx
  site/components/illustrations/components/audio-player/options/mute-button.tsx
  site/components/illustrations/components/audio-player/options/playback-speed-control.tsx
  site/components/illustrations/components/audio-player/options/recorded.tsx
  site/components/illustrations/components/audio-player/options/time-display.tsx
  site/components/illustrations/components/audio-player/options/volume-control.tsx
  site/components/illustrations/components/audio-player/usage/do-01.tsx
  site/components/illustrations/components/audio-player/usage/do-02.tsx
  site/components/illustrations/components/audio-player/usage/do-03.tsx
  site/components/illustrations/components/audio-player/usage/dont-01.tsx
  site/pages/components/audio-player-old.mdx
  site/pages/components/audio-player.tsx
  site/routes.ts
  site/templates/component-page-template/component-page-template.tsx
  site/templates/component-page-template/types.ts
  site/templates/template-sections/accessibility-section.tsx
  site/templates/template-sections/index.ts
  site/templates/template-sections/layout-examples-section.tsx
Labels: docs, ready for review

#362 chore(PPDSE-2397): chore-ppdse-2397-search-mobile-menu
  site/components/search/search.tsx
  site/components/site-header.tsx
Labels: ready for review

#349 docs(PPDSC-2298): NewsKit homepage update - What's New section
  site/components/feature-card/feature-card.tsx
  site/components/feature-card/types.ts
  site/components/homepage/explore/explore.tsx
  site/components/homepage/index.ts
  site/components/homepage/keep-in-touch/keep-in-touch.tsx
  site/components/homepage/supported-brands/supported-brands.tsx
  site/components/homepage/whats-new/index.ts
  site/components/homepage/whats-new/whats-new.tsx
  site/components/illustrations/brands/factiva.tsx
  site/components/illustrations/brands/index.ts
  site/pages/index-new.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  site/utils/release-notes/__tests__/functions.test.tsx
  site/utils/release-notes/types.ts
Labels: docs, ready for review

#264 feat(PPDSC-2115): accordion motion
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/accordion/__tests__/__snapshots__/accordion.test.tsx.snap
  src/accordion/__tests__/accordion.stories.tsx
  src/accordion/__tests__/accordion.test.tsx
  src/accordion/__tests__/utils.test.tsx
  src/accordion/accordion.tsx
  src/accordion/defaults.ts
  src/accordion/styled.ts
  src/accordion/types.ts
  src/accordion/utils.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/transition-presets.ts
Labels: feature

#366 chore(PPDSC-2280): chore-ppdse-2280-added prevent default
  src/consent/consent-settings-link.tsx
Labels: ready for review

#363 docs(PPDSC-2289): Text block documentation
  site/components/illustrations/components/text-block-illustration.tsx
  site/components/illustrations/components/text-block/anatomy.tsx
  site/components/illustrations/components/text-block/options/drop-cap.tsx
  site/components/illustrations/components/text-block/options/render.tsx
  site/components/illustrations/components/text-block/options/styling.tsx
  site/components/illustrations/components/text-block/options/text-crop.tsx
  site/components/illustrations/components/text-block/usage/do-01.tsx
  site/pages/components/text-block.mdx
  site/pages/components/text-block.tsx
  site/routes.ts
Labels: docs, ready for review

#352 feat(PPDSC-2322): add tealiumTrack to instrumentation
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/component-api/__tests__/component-api.test.tsx
  site/components/component-api/component-api.tsx
  site/components/component-api/types.ts
  site/pages/_app.tsx
  site/pages/components/divider.tsx
  site/pages/components/drawer.tsx
  site/pages/components/fieldset.tsx
  site/pages/components/modal.tsx
  site/pages/components/popover.tsx
  site/pages/components/text-block.tsx
  site/pages/components/tooltip.tsx
  site/pages/components/visibility.tsx
  site/pages/getting-started/code/instrumentation.tsx
  site/public/static/examples/instrumentation/instrumentation-provider.tsx
  site/templates/template-sections/__tests__/__snapshots__/component-api-section.test.tsx.snap
  src/instrumentation/handlers/__tests__/tealium-track-no-window.test.ts
  src/instrumentation/handlers/__tests__/tealium-track.test.ts
  src/instrumentation/handlers/index.ts
  src/instrumentation/handlers/tealium-track.ts
  src/tabs/types.ts
Labels: docs, ready for review

#367 fix(PPDSC-2413): textfield and select spacing issue
  site/pages/components/utils/get-css-from-theme.mdx
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/select-button.tsx
  src/select/styled.tsx
  src/text-field/__tests__/__snapshots__/text-field.test.tsx.snap
  src/text-field/__tests__/text-field.stories.tsx
  src/text-field/styled.tsx
  src/text-field/text-field.tsx
  src/text-field/types.ts
  src/utils/logical-properties.ts
  src/with-enhancers/styled.tsx
Labels: fix, ready for review

#360 docs(PPDSC-2301): newskit homepage hero interactive elements
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/homepage/hero/hero-interactive-elements.tsx
  site/components/homepage/hero/hero.tsx
  site/components/homepage/hero/styled.ts
  site/components/homepage/hero/types.ts
  site/components/homepage/keep-in-touch/keep-in-touch.tsx
  site/components/illustrations/landing-page/github.tsx
  site/components/illustrations/landing-page/hero-grid-logo.tsx
  site/components/illustrations/landing-page/medium.tsx
  site/components/illustrations/landing-page/storybook.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/styled.tsx
  site/components/theme-switch.tsx
  site/pages/index-new.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/slider/slider.tsx
  src/text-field/__tests__/__snapshots__/text-field.test.tsx.snap
  src/text-field/styled.tsx
Labels: docs, ready for review

#359 chore(PPDSC-2358): removed loading state for Tag and Flag components
  site/pages/components/tag.mdx
  src/button/styled.ts
  src/flag/flag.tsx
  src/flag/types.ts
  src/tag/tag.tsx
  src/tag/types.ts
Labels: ready for review, feature

#365 feat(PPDSC-2396): update no pointer distance for the tooltip and popover components
  site/pages/components/popover.tsx
  site/pages/components/tooltip.tsx
  src/base-floating-element/base-floating-element.tsx
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/__tests__/popover.stories.tsx
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/tooltip/__tests__/tooltip.stories.tsx
Labels: ready for review, feature

#373 fix(PPDSC-2312): audio player test improvements
  package.json
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player/__tests__/audio-player.stories.tsx
  src/audio-player/__tests__/auto-play-audio-player.stories.tsx
  src/popover/__tests__/popover.stories.tsx
  src/utils/audio-tests.tsx
Labels: fix, ready for review

#364 feat(PPDSC-2244): create text-area component
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/__tests__/__snapshots__/index.test.ts.snap
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/form/form-input.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/test/storybook-comps.tsx
  src/text-area/__tests__/__snapshots__/text-area.test.tsx.snap
  src/text-area/__tests__/text-area.stories.tsx
  src/text-area/__tests__/text-area.test.tsx
  src/text-area/defaults.ts
  src/text-area/index.tsx
  src/text-area/styled.tsx
  src/text-area/text-area.tsx
  src/text-area/types.ts
  src/text-field/__tests__/__snapshots__/text-field.test.tsx.snap
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/style-presets.ts
  src/utils/__tests__/style-preset.test.tsx
  src/utils/style/style-preset.ts
  yarn.lock
Labels: ready for review, feature

#376 docs(PPDSC-2420): introduce new homepage
  site/components/feature-card/feature-card.tsx
  site/components/illustrations/landing-page/hero-image.tsx
  site/components/index-cards.tsx
  site/pages/index-new.tsx
  site/pages/index.tsx
  site/public/static/landing/feature-card-contribute-old.svg
  site/public/static/landing/feature-card-roadmap.svg
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
Labels: docs, ready for review, feature

#368 docs(PPDSC-2331): Grid layout guide documentation
  site/components/illustrations/components/grid-layout/tutorials/designers.tsx
  site/components/illustrations/guides/grid-layout-guide/hero.tsx
  site/components/illustrations/guides/grid-layout-guide/steps/first-layout.tsx
  site/components/illustrations/guides/grid-layout-guide/steps/grid-layout.tsx
  site/components/illustrations/guides/grid-layout-guide/steps/responsive-props.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/media-list/media-list.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/grid-layout.tsx
  site/pages/getting-started/code/grid-layout-step-by-step.tsx
  site/routes.ts
  site/templates/component-page-template/component-page-template.tsx
  site/templates/component-page-template/types.ts
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
  site/templates/template-sections/index.ts
  site/templates/template-sections/tutorials-section.tsx
Labels: docs, ready for review

#378 fix(PPDSC-2402): select panel jumps to top of the page
  src/select/__tests__/select.stories.tsx
  src/select/select.tsx
Labels: fix, ready for review

#371 feat(PPDSE-2360): feat-2360-vertical-volume-control-gap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/types.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#377 docs(PPDSC-2286): Form guide documentation
  site/components/illustrations/guides/form-guide/hero.tsx
  site/components/illustrations/guides/form-guide/steps/step-01.tsx
  site/components/illustrations/guides/form-guide/steps/step-02.tsx
  site/components/illustrations/guides/form-guide/steps/step-03.tsx
  site/components/illustrations/guides/form-guide/steps/step-04.tsx
  site/components/illustrations/guides/form-guide/steps/step-05.tsx
  site/components/illustrations/guides/form-guide/steps/step-06.tsx
  site/components/illustrations/guides/form-guide/steps/step-07.tsx
  site/components/illustrations/guides/form-guide/steps/step-08.tsx
  site/components/illustrations/guides/form-guide/steps/step-09.tsx
  site/components/illustrations/guides/form-guide/steps/step-10.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/form.tsx
  site/pages/components/grid-layout.tsx
  site/pages/getting-started/code/form-step-by-step.tsx
  site/routes.ts
  site/templates/template-sections/tutorials-section.tsx
Labels: docs, ready for review

#383 fix(PPDSC-2361): fix tnl fonts
  site/pages/theme/theming/creating-a-theme.mdx
  site/public/static/examples/fonts/configuring-text-cropping.tsx
  site/public/static/examples/theming/font-crop-config.tsx
  src/theme-checker/themes/tnl-theme/fonts.json
  src/theme/__tests__/creator.test.ts
  src/theme/creator.ts
  src/theme/foundations/fonts.ts
  src/utils/__tests__/typography-preset.test.tsx
  src/utils/style/getters.ts
Labels: fix, ready for review

#381 feat(PPDSC-2403): Extend role and aria-haspopup on Popover
  src/popover/__tests__/popover.test.tsx
  src/popover/popover.tsx
Labels: feature

#379 docs(PPDSC-2383): search add label and filter results
  site/components/search/doc-search-hit.tsx
  site/components/search/search.tsx
  site/components/search/types.ts
  site/components/search/utils.ts
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  src/select/__tests__/select.stories.tsx
Labels: docs, ready for review

#388 docs(PPDSC-2357): Update on transition presets doc table
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/maxheightchange.tsx
  site/pages/theme/presets/transition-presets.tsx
Labels: docs, ready for review

#386 docs(PPDSC-2245): Text area documentation
  site/components/illustrations/components/text-area-illustration.tsx
  site/components/illustrations/components/text-area/anatomy.tsx
  site/components/illustrations/components/text-area/behaviours/truncation.tsx
  site/components/illustrations/components/text-area/behaviours/validation.tsx
  site/components/illustrations/components/text-area/options/autocomplete.tsx
  site/components/illustrations/components/text-area/options/character-count.tsx
  site/components/illustrations/components/text-area/options/height.tsx
  site/components/illustrations/components/text-area/options/max-and-min-length.tsx
  site/components/illustrations/components/text-area/options/multiple-text-areas.tsx
  site/components/illustrations/components/text-area/options/placeholder-text.tsx
  site/components/illustrations/components/text-area/options/resize-handle.tsx
  site/components/illustrations/components/text-area/options/size.tsx
  site/components/illustrations/components/text-area/options/width.tsx
  site/components/illustrations/components/text-area/states/base.tsx
  site/components/illustrations/components/text-area/states/disabled.tsx
  site/components/illustrations/components/text-area/states/focus.tsx
  site/components/illustrations/components/text-area/states/hover.tsx
  site/components/illustrations/components/text-area/states/invalid-focus.tsx
  site/components/illustrations/components/text-area/states/invalid-hover.tsx
  site/components/illustrations/components/text-area/states/invalid.tsx
  site/components/illustrations/components/text-area/states/read-only.tsx
  site/components/illustrations/components/text-area/states/selected.tsx
  site/components/illustrations/components/text-area/states/valid-focus.tsx
  site/components/illustrations/components/text-area/states/valid-hover.tsx
  site/components/illustrations/components/text-area/states/valid.tsx
  site/components/illustrations/components/text-area/usage/do-01.tsx
  site/components/illustrations/components/text-area/usage/do-02.tsx
  site/components/illustrations/components/text-area/usage/do-03.tsx
  site/components/illustrations/components/text-area/usage/do-04.tsx
  site/components/illustrations/components/text-area/usage/dont-01.tsx
  site/components/illustrations/components/text-area/usage/dont-02.tsx
  site/components/illustrations/components/text-area/usage/dont-03.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/text-area.tsx
  site/routes.ts
Labels: docs, ready for review

#387 feat(PPDSC-2384): add new start screen to search modal
  cypress/site/functional/search.spec.js
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/search/__tests__/__snapshots__/new-start-screen.test.ts.snap
  site/components/search/__tests__/new-start-screen.test.ts
  site/components/search/new-start-screen.tsx
  site/components/search/search.tsx
  site/components/site-header.tsx
Labels: ready for review, feature

#338 chore(PPDSC-2234): investigate Storybook analytics
  .storybook/addons/tealium/preset.js
  .storybook/addons/tealium/register.js
  .storybook/main.js
  package.json
  site/pages/_document.tsx
  src/tealium/__tests__/__snapshots__/tealium.test.tsx.snap
  src/tealium/tealium.tsx
  yarn.lock
Labels: ready for review
