Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-03, with the labels that each got.

#95 Feat/ppdsc 2011 audio player playpause
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/__tests__/utils.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/audio-element.tsx
  src/audio-player-composable/components/play-pause-button.tsx
  src/audio-player-composable/context.tsx
  src/audio-player-composable/types.ts
  src/audio-player-composable/utils.ts
Labels: ready for review, feature

#104 feat(PPDSC-2042): update issue templates
  .github/ISSUE_TEMPLATE/a11y_investigation.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/story.md
  .github/ISSUE_TEMPLATE/task.md
Labels: ready for review

#106 feat(PPDSC-2019): Replace contact us form
  site/pages/about/contact-us.tsx
Labels: ready for review, feature

#107 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: docs, ready for review

#84 feat(PPDSC-1981): logical props 1 of 6
  src/assistive-text/__tests__/__snapshots__/assistive-text.test.tsx.snap
  src/block/__tests__/block.stories.tsx
  src/block/block.tsx
  src/button/styled.ts
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/flag/styled.ts
  src/flag/types.ts
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/form/types.ts
  src/label/styled.tsx
  src/label/types.ts
  src/link/internal-link.tsx
  src/link/types.ts
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/styled.tsx
  src/select/types.ts
  src/stack/styled.ts
  src/stack/types.ts
  src/text-block/text-block.tsx
  src/text-block/types.ts
  src/text-field/__tests__/__snapshots__/text-field.test.tsx.snap
  src/utils/__tests__/logical-properties.test.ts
  src/utils/logical-properties.ts
  src/with-enhancers/styled.tsx
Labels: ready for review, feature

#108 feat(PPDSC-2031): audio player seekbar
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/__tests__/utils.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/audio-element.tsx
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/play-pause-button/types.ts
  src/audio-player-composable/components/seek-bar/defaults.ts
  src/audio-player-composable/components/seek-bar/seek-bar.tsx
  src/audio-player-composable/components/seek-bar/style-presets.ts
  src/audio-player-composable/components/seek-bar/types.ts
  src/audio-player-composable/components/seek-bar/utils.ts
  src/audio-player-composable/context.tsx
  src/audio-player-composable/types.ts
  src/audio-player-composable/utils.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#111 docs(PPDSC-2010): Transitions presets
  site/components/base-card/base-card.tsx
  site/components/illustrations/theme/transition-presets/hero.tsx
  site/components/illustrations/theme/transition-presets/overview.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/backgroundcolorchange.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/bordercolorchange.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/fade.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/fontcolorchange.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/grow.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/iconcolorchange.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/moveup.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/slidebottom.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/slideleft.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/slideright.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/slidetop.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/base.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/enter.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/enteractive.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/enterdone.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/exit.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/exitactive.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/component/exitdone.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/overview.tsx
  site/components/illustrations/theme/transition-presets/transition-preset-states/user-interaction.tsx
  site/components/illustrations/theme/transition-presets/transition-presets-in-figma.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/pages/theme/presets/style-presets.tsx
  site/pages/theme/presets/transition-presets.tsx
  site/pages/theme/presets/typography-presets.tsx
  site/public/static/examples/transition-presets/background-border-colours.mp4
  site/public/static/examples/transition-presets/background-colour.mp4
  site/public/static/examples/transition-presets/drawer-mount-unmount.mp4
  site/routes.ts
Labels: docs, ready for review

#115 fix(PPDSC-2014): add 404 page
  Makefile
  cypress/site/functional/404.spec.js
  docs/scripts.md
  package.json
  scripts/post-build.js
  site/pages/404.tsx
Labels: fix, ready for review

#103 feat(PPDSC-2032): audio player time display
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/__tests__/utils.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/play-pause-button/index.ts
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/seek-bar/defaults.ts
  src/audio-player-composable/components/seek-bar/index.ts
  src/audio-player-composable/components/seek-bar/seek-bar.tsx
  src/audio-player-composable/components/time-display/defaults.ts
  src/audio-player-composable/components/time-display/index.ts
  src/audio-player-composable/components/time-display/style-presets.ts
  src/audio-player-composable/components/time-display/time-display.tsx
  src/audio-player-composable/components/time-display/types.ts
  src/audio-player-composable/components/time-display/utils.tsx
  src/audio-player-composable/context.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/index.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#109 feat(PPDSC-2020): add radio-button and group
  scripts/generate-icons/icons-full-list.js
  scripts/generate-icons/used-icons-list.json
  site/components/illustrations/components/radio-button/radio-button-illustration.tsx
  site/pages/components/radio-button.tsx
  site/routes.ts
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/__tests__/__snapshots__/index.test.ts.snap
  src/base-switch/base-switch.tsx
  src/base-switch/index.tsx
  src/base-switch/styled.tsx
  src/base-switch/types.ts
  src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
  src/checkbox/__tests__/checkbox.stories.tsx
  src/checkbox/__tests__/helpers.tsx
  src/checkbox/checkbox.tsx
  src/checkbox/style-presets.ts
  src/checkbox/types.ts
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/form/__tests__/form-input.stories.tsx
  src/form/__tests__/form.test.tsx
  src/form/form-input.tsx
  src/form/utils.tsx
  src/grid-layout/types.ts
  src/index.ts
  src/radio-button/__tests__/helpers.tsx
  src/radio-button/__tests__/radio-button.stories.tsx
  src/radio-button/__tests__/radio-button.test.tsx
  src/radio-button/defaults.ts
  src/radio-button/index.tsx
  src/radio-button/radio-button.tsx
  src/radio-button/radio-group.tsx
  src/radio-button/style-presets.ts
  src/radio-button/types.ts
  src/theme-checker/scenarios.tsx
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/style-presets.ts
  src/utils/__tests__/__snapshots__/style-preset.test.tsx.snap
  src/utils/__tests__/style-preset.test.tsx
  src/utils/compose-event-handlers.ts
  src/utils/hooks/use-controlled.ts
  src/utils/style/style-preset.ts
Labels: ready for review, feature

#116 feat(PPDSC-2028): update checkbox style preset
  src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
  src/checkbox/__tests__/helpers.tsx
  src/checkbox/style-presets.ts
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#118 fix(PPDSC-2025): Tabbing into a checkbox breaks form validation
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/form/__tests__/form.stories.tsx
  src/form/__tests__/form.test.tsx
  src/form/form-entry.tsx
  src/form/form-input.tsx
  src/text-input/text-input.tsx
Labels: fix, ready for review

#119 feat(PPDSC-2009): add reduced motion to transitionPreset
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/icons/__tests__/__snapshots__/icons.test.tsx.snap
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/meta/__tests__/__snapshots__/meta.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/step/__tests__/__snapshots__/step.test.tsx.snap
  site/components/table-of-contents/__tests__/__snapshots__/table-of-contents.test.tsx.snap
  site/components/table/__tests__/__snapshots__/table.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  site/components/tools/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/components/usage-card/__tests__/__snapshots__/usage-card.test.tsx.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/audio-player/__tests__/__snapshots__/popout-button.test.tsx.snap
  src/banner/__tests__/__snapshots__/banner.test.tsx.snap
  src/block/__tests__/__snapshots__/block.test.tsx.snap
  src/button/__tests__/__snapshots__/button.test.tsx.snap
  src/byline/__tests__/__snapshots__/byline.test.tsx.snap
  src/card/__tests__/__snapshots__/card.test.tsx.snap
  src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
  src/consent/__tests__/__snapshots__/consent-settings-link.test.tsx.snap
  src/dialog/types.ts
  src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/flag/__tests__/__snapshots__/flag.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/icon-button/__tests__/__snapshots__/icon-button.test.tsx.snap
  src/icons/__tests__/__snapshots__/custom-icons.test.tsx.snap
  src/icons/__tests__/__snapshots__/material-icons.test.tsx.snap
  src/image/__tests__/__snapshots__/image.test.tsx.snap
  src/inline-message/__tests__/__snapshots__/inline-message.test.tsx.snap
  src/link/__tests__/__snapshots__/link.test.tsx.snap
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/modal/__tests__/__snapshots__/modal.test.tsx.snap
  src/overlay/__tests__/__snapshots__/overlay.test.tsx.snap
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/share-bar/__tests__/__snapshots__/share-bar.test.tsx.snap
  src/slider/__tests__/__snapshots__/slider.test.tsx.snap
  src/stack-child/__tests__/__snapshots__/stack-child.test.tsx.snap
  src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap
  src/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
  src/tag/__tests__/__snapshots__/tag.test.tsx.snap
  src/text-field/__tests__/__snapshots__/text-field.test.tsx.snap
  src/text-input/__tests__/__snapshots__/text-input.test.tsx.snap
  src/title-bar/__tests__/__snapshots__/title-bar.test.tsx.snap
  src/toast/__tests__/__snapshots__/toast.test.tsx.snap
  src/unordered-list/__tests__/__snapshots__/unordered-list.test.tsx.snap
  src/utils/__tests__/__snapshots__/default-functions.test.ts.snap
  src/utils/__tests__/default-functions.test.ts
  src/utils/__tests__/get-transition-duration.test.ts
  src/utils/__tests__/transition-preset.test.ts
  src/utils/get-transition-duration.ts
  src/utils/style/transition-preset.ts
  src/volume-control/__tests__/__snapshots__/volume-control.test.tsx.snap
Labels: ready for review, feature

#122 feat(PPDSC-2049): audio player replay forward buttons
  cypress/components/audio-player-composable.spec.js
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/forward-button/defaults.ts
  src/audio-player-composable/components/forward-button/forward-button.tsx
  src/audio-player-composable/components/forward-button/index.ts
  src/audio-player-composable/components/replay-button/defaults.ts
  src/audio-player-composable/components/replay-button/index.ts
  src/audio-player-composable/components/replay-button/replay-button.tsx
  src/audio-player-composable/components/time-display/time-display.tsx
  src/audio-player-composable/components/time-display/types.ts
  src/audio-player-composable/context.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/utils/types.ts
Labels: ready for review, feature

#129 docs(PPDSC-2022): Radio button page
  site/components/illustrations/components/radio-button/anatomy.tsx
  site/components/illustrations/components/radio-button/behaviours/autofocus.tsx
  site/components/illustrations/components/radio-button/behaviours/clickable-area.tsx
  site/components/illustrations/components/radio-button/behaviours/default-checked.tsx
  site/components/illustrations/components/radio-button/behaviours/exclusive-selection.tsx
  site/components/illustrations/components/radio-button/behaviours/focusable-area.tsx
  site/components/illustrations/components/radio-button/behaviours/label-overflow-wrap.tsx
  site/components/illustrations/components/radio-button/behaviours/transition.tsx
  site/components/illustrations/components/radio-button/behaviours/validation.tsx
  site/components/illustrations/components/radio-button/options/feedback.tsx
  site/components/illustrations/components/radio-button/options/fieldset.tsx
  site/components/illustrations/components/radio-button/options/icon.tsx
  site/components/illustrations/components/radio-button/options/label.tsx
  site/components/illustrations/components/radio-button/options/radio-group.tsx
  site/components/illustrations/components/radio-button/options/size.tsx
  site/components/illustrations/components/radio-button/states/base.tsx
  site/components/illustrations/components/radio-button/states/checked-disabled.tsx
  site/components/illustrations/components/radio-button/states/checked-focus-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-focus.tsx
  site/components/illustrations/components/radio-button/states/checked-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-invalid-focus-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-invalid-focus.tsx
  site/components/illustrations/components/radio-button/states/checked-invalid-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-invalid.tsx
  site/components/illustrations/components/radio-button/states/checked-valid-focus-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-valid-focus.tsx
  site/components/illustrations/components/radio-button/states/checked-valid-hover.tsx
  site/components/illustrations/components/radio-button/states/checked-valid.tsx
  site/components/illustrations/components/radio-button/states/checked.tsx
  site/components/illustrations/components/radio-button/states/disabled.tsx
  site/components/illustrations/components/radio-button/states/focus-hover.tsx
  site/components/illustrations/components/radio-button/states/focus.tsx
  site/components/illustrations/components/radio-button/states/hover.tsx
  site/components/illustrations/components/radio-button/states/invalid-focus-hover.tsx
  site/components/illustrations/components/radio-button/states/invalid-focus.tsx
  site/components/illustrations/components/radio-button/states/invalid-hover.tsx
  site/components/illustrations/components/radio-button/states/invalid.tsx
  site/components/illustrations/components/radio-button/states/valid-focus-hover.tsx
  site/components/illustrations/components/radio-button/states/valid-focus.tsx
  site/components/illustrations/components/radio-button/states/valid-hover.tsx
  site/components/illustrations/components/radio-button/states/valid.tsx
  site/components/illustrations/components/radio-button/usage/do-1.tsx
  site/components/illustrations/components/radio-button/usage/do-2.tsx
  site/components/illustrations/components/radio-button/usage/do-3.tsx
  site/components/illustrations/components/radio-button/usage/do-4.tsx
  site/components/illustrations/components/radio-button/usage/dont-1.tsx
  site/components/illustrations/components/radio-button/usage/dont-2.tsx
  site/components/illustrations/components/radio-button/usage/validation.tsx
  site/components/meta/introduce.tsx
  site/pages/components/checkbox.tsx
  site/pages/components/radio-button.tsx
Labels: docs, ready for review

#125 feat(PPDSC-2034): audio player keyboard shortcuts
  cypress/components/audio-player-composable.spec.js
  package.json
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/audio-element.tsx
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/play-pause-button/types.ts
  src/audio-player-composable/components/time-display/types.ts
  src/audio-player-composable/context.tsx
  src/audio-player-composable/types.ts
  src/grid-layout/types.ts
  src/utils/hooks/__tests__/use-keypress.test.ts
  src/utils/hooks/use-keypress.ts
  yarn.lock
Labels: ready to merge, ready for review, feature

#127 feat(PPDSC-2039): audio player event handler
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/audio-element.tsx
  src/audio-player-composable/context.tsx
  src/audio-player-composable/types.ts
Labels: ready to merge, ready for review, feature

#135 docs(PPDSC-2029): update page title
  site/pages/about/contact-us.tsx
  site/pages/components/inline-message.tsx
  site/pages/components/share-bar.tsx
  site/pages/getting-started/design/design-overview.tsx
  site/routes.ts
Labels: docs, ready for review

#136 fix(PPDSC-2033): stylePreset at theme level
  site/pages/theme/theming/creating-a-theme.mdx
  src/utils/hooks/use-media-query/context.tsx
  src/utils/with-own-theme.tsx
Labels: fix, ready for review

#132 feat(PPDSC-2048): audio player next prev button
  cypress/components/audio-player-composable.spec.js
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/play-pause-button/defaults.ts
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/play-pause-button/types.ts
  src/audio-player-composable/components/skip-next/defaults.ts
  src/audio-player-composable/components/skip-next/index.ts
  src/audio-player-composable/components/skip-next/skip-next.tsx
  src/audio-player-composable/components/skip-previous/defaults.ts
  src/audio-player-composable/components/skip-previous/index.ts
  src/audio-player-composable/components/skip-previous/skip-previous.tsx
  src/audio-player-composable/components/time-display/time-display.tsx
  src/audio-player-composable/context.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/utils/types.ts
Labels: ready for review, feature

#139 chore(PPDSC-2046): review PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/testing.md
Labels: good first issue, ready for review, task
