Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-05, with the labels that each got.

#186 feat(PPDSC-2072): enable applitools logs
  package.json
  yarn.lock
Labels: feature

#187 feat(PPDSC-1942): add Safari specific css to tabs
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  src/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
  src/tabs/styled.tsx
Labels: ready for review, feature

#179 docs(PPDSC-1976): Media list fix
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
  src/card/__tests__/__snapshots__/card.test.tsx.snap
  src/card/styled.tsx
Labels: enhancement, docs, ready for review

#184 feat(PPDSC-2107): add tracking support to structured list and text field
  site/pages/components/menu.tsx
  site/pages/components/structured-list.tsx
  site/pages/components/text-field.tsx
  site/pages/getting-started/code/instrumentation.tsx
  src/instrumentation/types.ts
  src/structured-list/__tests__/structured-list.test.tsx
  src/structured-list/structured-list-item.tsx
  src/structured-list/types.ts
  src/text-field/__tests__/text-field.test.tsx
  src/text-field/text-field.tsx
  src/text-field/types.ts
Labels: ready for review, feature

#183 ci(PPDSC-2017): newskit integration test
  .circleci/config.yml
  Makefile
  scripts/templates-integration-test/cypress.json
  scripts/templates-integration-test/index.txt
  scripts/templates-integration-test/theme-checker.spec.js
Labels: ready for review, feature

#189 docs(PPDSC-2133): Fieldset
  site/components/illustrations/components/fieldset/anatomy.tsx
  site/components/illustrations/components/fieldset/form-structure.tsx
  site/components/illustrations/components/fieldset/hero.tsx
  site/components/illustrations/components/fieldset/options/legend.tsx
  site/components/illustrations/components/fieldset/options/size.tsx
  site/components/illustrations/components/fieldset/states/base.tsx
  site/components/illustrations/components/fieldset/states/disabled.tsx
  site/pages/components/fieldset.tsx
  site/routes.ts
  site/templates/component-page-template/component-page-template.tsx
  site/templates/component-page-template/types.ts
  site/templates/template-sections/common-section.tsx
Labels: docs, ready for review

#195 docs(PPDSC-2149): Updated structured-list page link
  site/pages/components/structured-list.tsx
  site/routes.ts
  site/templates/template-sections/anatomy-section.tsx
Labels: docs, ready for review

#196 fix(PPDSC-2160): back to newskit folder
  .circleci/config.yml
Labels: fix

#197 Fix/ppdsc 2160 fix npm publish release
  .circleci/config.yml
Labels: fix

#198 docs(PPDSC-2138): Updated testing card
  site/components/illustrations/components/grid-layout-illustration.tsx
  site/components/illustrations/guides/overview/testing.tsx
  site/components/sidebar/types.ts
  site/pages/components/grid-layout.tsx
  site/pages/getting-started/overview.tsx
  site/routes.ts
Labels: docs, ready for review

#200 feat(PPDSC-2067): audio player v2 live functionality stories and tests
  scripts/generate-icons/used-icons-list.json
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
Labels: ready for review, feature, ready for design review

#194 Fix/ppdsc 2113 prodtealium not being served
  .circleci/config.yml
  site/pages/_document.tsx
Labels: fix, ready for review

#201 docs(PPDSC-2139): remove grey background on header comp
  site/components/header-index/__tests__/__snapshots__/header-index.test.tsx.snap
  site/components/header-index/header-index.tsx
Labels: docs, ready for review

#202 feat(PPDSC-2095): add opacity tokens and gradients to the theme
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/overlays.ts
  src/theme/presets/__tests__/style-presets.test.ts
  src/theme/presets/style-presets.ts
  src/theme/presets/transition-presets.ts
Labels: ready for review, feature

#203 feat(PPDSC-2123): add link to the Handoff guide for engineers to the site
  site/pages/getting-started/code/engineering-overview.tsx
Labels: ready for review, feature

#191 feat(PPDSC-1984): logical props 4
  site/components/component-api/common-logical-props.tsx
  site/pages/components/drawer.tsx
  site/pages/components/headline.mdx
  site/pages/components/icons.mdx
  site/pages/components/image.mdx
  site/pages/components/inline-message.tsx
  site/pages/components/menu.tsx
  site/pages/components/modal.tsx
  site/pages/components/ordered-list.mdx
  site/pages/components/toast.tsx
  src/headline/__tests__/__snapshots__/headline.test.tsx.snap
  src/headline/__tests__/headline.stories.tsx
  src/headline/__tests__/headline.test.tsx
  src/headline/headline.tsx
  src/headline/types.ts
  src/icon-button/__tests__/__snapshots__/icon-button.test.tsx.snap
  src/icon-button/__tests__/icon-button.stories.tsx
  src/icon-button/__tests__/icon-button.test.tsx
  src/icons/__tests__/__snapshots__/material-icons.test.tsx.snap
  src/icons/__tests__/icons.stories.tsx
  src/icons/__tests__/material-icons.test.tsx
  src/icons/to-newskit-icon.tsx
  src/icons/types.ts
  src/image/__tests__/__snapshots__/image.test.tsx.snap
  src/image/__tests__/image.stories.tsx
  src/image/__tests__/image.test.tsx
  src/image/styled.ts
  src/image/types.ts
  src/inline-message/__tests__/__snapshots__/inline-message.test.tsx.snap
  src/inline-message/__tests__/inline-message.stories.tsx
  src/inline-message/__tests__/inline-message.test.tsx
  src/inline-message/types.ts
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/menu/__tests__/menu.stories.tsx
  src/menu/__tests__/menu.test.tsx
  src/menu/styled.tsx
  src/menu/types.ts
  src/modal/__tests__/__snapshots__/modal.test.tsx.snap
  src/modal/__tests__/modal.stories.tsx
  src/modal/__tests__/modal.test.tsx
  src/modal/styled.ts
  src/modal/types.ts
  src/ordered-list/__tests__/__snapshots__/ordered-list.test.tsx.snap
  src/ordered-list/__tests__/ordered-list.stories.tsx
  src/ordered-list/__tests__/ordered-list.test.tsx
  src/ordered-list/ordered-list.tsx
  src/ordered-list/types.ts
  src/toast/__tests__/__snapshots__/toast.test.tsx.snap
  src/toast/__tests__/toast.stories.tsx
  src/toast/__tests__/toast.test.tsx
  src/toast/styled.tsx
  src/toast/toast.tsx
  src/toast/types.ts
Labels: ready for review, feature

#193 feat(PPDSC-2135): add unified script to Consent
  cypress/support/commands.js
  site/components/site-footer.tsx
  site/pages/_document.tsx
  site/pages/components/consent-settings-link.mdx
  site/pages/components/consent.mdx
  site/public/static/examples/consent.tsx
  src/consent/__tests__/__snapshots__/consent.test.tsx.snap
  src/consent/__tests__/consent-settings-link.test.tsx
  src/consent/__tests__/consent.test.tsx
  src/consent/consent-settings-link.tsx
  src/consent/consent-utils.ts
  src/consent/consent.tsx
  src/consent/types.ts
Labels: ready for review, feature

#205 docs(PPDSC-2082): Update contribute page
  site/components/page-introduction/page-introduction.tsx
  site/components/page-introduction/types.ts
  site/pages/about/contribute.tsx
Labels: enhancement, docs, ready for review

#182 feat(PPDSC-2078): switch v1
  scripts/generate-icons/used-icons-list.json
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/__tests__/__snapshots__/index.test.ts.snap
  src/base-switch/base-switch.tsx
  src/base-switch/styled.tsx
  src/base-switch/types.ts
  src/checkbox/types.ts
  src/index.ts
  src/radio-button/types.ts
  src/switch/__tests__/__snapshots__/switch.test.tsx.snap
  src/switch/__tests__/helpers.tsx
  src/switch/__tests__/switch.stories.tsx
  src/switch/__tests__/switch.test.tsx
  src/switch/defaults.ts
  src/switch/index.tsx
  src/switch/style-presets.ts
  src/switch/styled.tsx
  src/switch/switch.tsx
  src/switch/types.ts
  src/theme-checker/scenarios.tsx
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/transition-presets.ts
  src/utils/logical-properties.ts
Labels: ready for review, feature, ready for design review

#206 fix(PPDSC-2047): Resolve gaps in buffering seekbar by refactoring formatTrackData
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/__tests__/utils.test.tsx
  src/audio-player-composable/components/seek-bar/utils.ts
Labels: fix, ready for review

#204 feat(PPDSC-2117): tooltip panel and content
  package.json
  src/__tests__/__snapshots__/index.test.ts.snap
  src/button/types.ts
  src/icon-button/__tests__/icon-button.test.tsx
  src/icon-button/icon-button.tsx
  src/icon-button/types.ts
  src/index.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/tooltip/__tests__/tooltip.stories.tsx
  src/tooltip/__tests__/tooltip.test.tsx
  src/tooltip/defaults.ts
  src/tooltip/index.ts
  src/tooltip/style-presets.ts
  src/tooltip/styled.tsx
  src/tooltip/tooltip.tsx
  src/tooltip/types.ts
  yarn.lock
Labels: ready for review, feature

#207 docs(PPDSC-2150): Structured list page
  site/components/illustrations/components/structured-list/anatomy.tsx
  site/components/illustrations/components/structured-list/behaviours-alignment.tsx
  site/components/illustrations/components/structured-list/hero.tsx
  site/components/illustrations/components/structured-list/options/options-divider.tsx
  site/components/illustrations/components/structured-list/options/options-interactive.tsx
  site/components/illustrations/components/structured-list/options/options-item-and-cell-layouts.tsx
  site/components/illustrations/components/structured-list/states/active.tsx
  site/components/illustrations/components/structured-list/states/base.tsx
  site/components/illustrations/components/structured-list/states/disabled.tsx
  site/components/illustrations/components/structured-list/states/focus.tsx
  site/components/illustrations/components/structured-list/states/hover.tsx
  site/pages/components/structured-list.tsx
  site/routes.ts
Labels: docs, ready for review

#215 fix(PPDSC-2198): update SSL Cert ARNs
  eks/values/product-platforms-values-dev.yaml
  eks/values/product-platforms-values-prod.yaml
Labels: fix

#210 docs(PPDSC-2096): Update with new tokens and states
  site/components/illustrations/theme/style-presets/hover-active.tsx
  site/components/illustrations/theme/style-presets/invalid-hover-active.tsx
  site/components/illustrations/theme/style-presets/selected-focus.tsx
  site/components/illustrations/theme/style-presets/selected-hover.tsx
  site/components/illustrations/theme/style-presets/selected.tsx
  site/components/illustrations/theme/style-presets/valid-hover-active.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/opacitychange.tsx
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/shiftabsolute.tsx
  site/pages/theme/colours.tsx
  site/pages/theme/presets/style-presets.tsx
  site/pages/theme/presets/transition-presets.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/utils/colors-token-description.tsx
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/colors.ts
Labels: docs, ready for review
