Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-08, with the labels that each got.

#318 docs(PPDSC-2259): skeleton of homepage
  site/components/site-footer.tsx
  site/pages/index-new.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
Labels: docs, ready for review

#321 feat(PPDSC-2313): script to run applitools locally
  docs/scripts.md
  package.json
  scripts/applitools_local.sh
Labels: ready for review, feature

#320 docs(PPDSC-2334): update docs
  site/pages/components/image.mdx
Labels: docs, ready for review

#317 docs(PPDSC-2252): Misc updates on the site
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/table/column-renderer.tsx
  site/pages/components/accordion.tsx
  site/pages/components/banner.tsx
  site/pages/components/block.tsx
  site/pages/components/button.tsx
  site/pages/components/checkbox.tsx
  site/pages/components/divider.tsx
  site/pages/components/drawer.tsx
  site/pages/components/fieldset.tsx
  site/pages/components/inline-message.tsx
  site/pages/components/menu.tsx
  site/pages/components/modal.tsx
  site/pages/components/popover.tsx
  site/pages/components/radio-button.tsx
  site/pages/components/select.tsx
  site/pages/components/share-bar.tsx
  site/pages/components/structured-list.tsx
  site/pages/components/tabs.tsx
  site/pages/components/text-field.tsx
  site/pages/components/toast.tsx
  site/pages/components/tooltip.tsx
  site/pages/components/visibility.tsx
  site/pages/getting-started/design/design-overview.tsx
  site/pages/theme/foundation/colours.tsx
  site/pages/theme/foundation/fonts.tsx
  site/pages/theme/foundation/iconography.tsx
  site/pages/theme/foundation/motion.tsx
  site/pages/theme/foundation/sizing.tsx
  site/pages/theme/foundation/spacing.tsx
  site/public/static/theming/foundations/balanced-spacing.svg
  site/public/static/theming/foundations/balanced.svg
  site/public/static/theming/foundations/borders.svg
  site/public/static/theming/foundations/breakpoints.svg
  site/public/static/theming/foundations/colours.svg
  site/public/static/theming/foundations/consistent.svg
  site/public/static/theming/foundations/contextual-colours.svg
  site/public/static/theming/foundations/contextual.svg
  site/public/static/theming/foundations/expressive-colours.svg
  site/public/static/theming/foundations/flow.svg
  site/public/static/theming/foundations/functional.svg
  site/public/static/theming/foundations/guided.svg
  site/public/static/theming/foundations/inclusive-colours.svg
  site/public/static/theming/foundations/instinctive.svg
  site/public/static/theming/foundations/legible.svg
  site/public/static/theming/foundations/motion.svg
  site/public/static/theming/foundations/overlays.svg
  site/public/static/theming/foundations/proportional.svg
  site/public/static/theming/foundations/purposeful-fonts.svg
  site/public/static/theming/foundations/purposeful.svg
  site/public/static/theming/foundations/relational.svg
  site/public/static/theming/foundations/seamless.svg
  site/public/static/theming/foundations/shadows.svg
  site/public/static/theming/foundations/simple.svg
  site/public/static/theming/foundations/sizing.svg
  site/public/static/theming/foundations/typography.svg
  site/routes.ts
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
  site/templates/template-sections/related-components-section.tsx
Labels: docs, ready for review

#323 feat(EOP-253): add async support to experimentation web
  site/pages/components/experimentation-web.mdx
  src/experimentation-web/__tests__/__snapshots__/experimentation-web.test.tsx.snap
  src/experimentation-web/__tests__/experimentation-web.test.tsx
  src/experimentation-web/experimentation-web.tsx
  src/experimentation-web/types.tsx
Labels: ready for review, feature

#325 fix(PPDSC-2304): useBreakpointKey incorrect state
  src/utils/hooks/use-media-query/context.tsx
Labels: fix, ready for review

#319 docs(PPDSC-2204): release notes
  package.json
  site/components/content-structure/content-section.tsx
  site/components/content-structure/types.tsx
  site/components/illustrations/about/release-notes-hero-illustration.tsx
  site/components/release-notes/__tests__/__snapshots__/release-badges.test.tsx.snap
  site/components/release-notes/__tests__/__snapshots__/release-header.test.tsx.snap
  site/components/release-notes/__tests__/__snapshots__/release-notes.test.tsx.snap
  site/components/release-notes/__tests__/release-badges.test.tsx
  site/components/release-notes/__tests__/release-header.test.tsx
  site/components/release-notes/__tests__/release-notes.test.tsx
  site/components/release-notes/release-badges.tsx
  site/components/release-notes/release-header.tsx
  site/components/release-notes/release-notes.tsx
  site/pages/about/release-notes.mdx
  site/pages/about/release-notes.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  site/utils/release-notes/__tests__/functions.test.tsx
  site/utils/release-notes/constants.ts
  site/utils/release-notes/functions.ts
  site/utils/release-notes/types.ts
  yarn.lock
Labels: docs, ready for review

#306 Feat/ppdsc 2143 volume control horizontal expand
  site/components/illustrations/theme/transition-presets/predefined-transition-presets/widthchange.tsx
  site/pages/theme/presets/transition-presets.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/styled.ts
  src/audio-player-composable/components/volume-control/types.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/audio-player-composable/types.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/transition-presets.ts
Labels: ready for review, feature

#324 Feat(PPDSC-2315): implement Applitools spike recommendations
  .circleci/config.yml
  applitools.components.config.js
  applitools.config.js
  package.json
Labels: ready for review, feature

#322 feat(PPDSC-2314): audio player - playback speed custom children trigger
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/playback-speed-control/playback-speed-control.tsx
  src/audio-player-composable/components/playback-speed-control/types.ts
Labels: ready for review, feature

#295 Feat/ppdsc 2253 storybook scenarios and UL default updates
  .gitignore
  lib/codemod/.eslintignore
  lib/codemod/README.md
  lib/codemod/src/cli.js
  lib/codemod/src/transforms/__tests__/remove-redundant-marker-ul/actual.jsx
  lib/codemod/src/transforms/__tests__/remove-redundant-marker-ul/expected.jsx
  lib/codemod/src/transforms/__tests__/remove-redundant-marker-ul/remove-redundant-marker-ul.test.js
  lib/codemod/src/transforms/__tests__/update-list-item-marker-ul-value.js/actual.js
  lib/codemod/src/transforms/__tests__/update-list-item-marker-ul-value.js/expected.js
  lib/codemod/src/transforms/__tests__/update-list-item-marker-ul-value.js/update-list-item-marker-ul-value.test.js
  lib/codemod/src/transforms/remove-redundant-marker-ul.js
  lib/codemod/src/transforms/update-list-item-marker-ul-value.js
  lib/codemod/src/utils/add-prop.js
  site/pages/components/modal.tsx
  site/pages/components/slider.mdx
  site/pages/components/unordered-list.mdx
  site/pages/getting-started/code/engineering-quickstart.tsx
  site/pages/getting-started/code/instrumentation.tsx
  site/pages/getting-started/design/design-quickstart.tsx
  site/pages/help/terms-and-conditions.tsx
  site/pages/patterns/forms/address.tsx
  site/pages/patterns/forms/best-practice.tsx
  site/pages/patterns/forms/date-of-birth.tsx
  site/pages/patterns/forms/date-picker.tsx
  site/pages/patterns/forms/email-address.tsx
  site/pages/patterns/forms/gender.tsx
  site/pages/patterns/forms/input-components.tsx
  site/pages/patterns/forms/names.tsx
  site/pages/patterns/forms/passwords.tsx
  site/pages/patterns/forms/payment.tsx
  site/pages/patterns/forms/telephone-number.tsx
  site/pages/theme/foundation/motion.tsx
  src/unordered-list/__tests__/__snapshots__/unordered-list.test.tsx.snap
  src/unordered-list/__tests__/unordered-list.stories.tsx
  src/unordered-list/__tests__/unordered-list.test.tsx
  src/unordered-list/types.ts
  src/unordered-list/unordered-list.tsx
Labels: ready for review, feature, breaking change

#329 docs(PPDSC-2299): newskit new homepage hero section
  site/components/homepage/hero/hero.tsx
  site/components/homepage/hero/index.ts
  site/components/homepage/hero/styled.ts
  site/components/homepage/hero/types.ts
  site/components/homepage/index.ts
  site/components/illustrations/landing-page/hero-grid.tsx
  site/pages/index-new.tsx
Labels: docs, ready for review

#331 feat(PPDSC-2163): codemods for enums
  .gitignore
  lib/codemod/README.md
  lib/codemod/src/cli.js
  lib/codemod/src/transforms/__tests__/enums-to-union/actual.js
  lib/codemod/src/transforms/__tests__/enums-to-union/enum-to-union.test.js
  lib/codemod/src/transforms/__tests__/enums-to-union/expected.js
  lib/codemod/src/transforms/enum-to-union.js
  lib/codemod/src/utils/__tests__/to-kebab-case.test.js
  lib/codemod/src/utils/to-kebab-case.js
Labels: ready for review, feature

#334 feat(PPDSC-2274): vertical volume control in Popover
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/style-presets.ts
  src/audio-player-composable/components/volume-control/styled.ts
  src/audio-player-composable/components/volume-control/types.ts
  src/audio-player-composable/components/volume-control/utils.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/audio-player-composable/types.ts
  src/base-floating-element/base-floating-element.tsx
  src/base-floating-element/types.ts
  src/popover/popover.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/types.ts
Labels: ready for review, feature

#332 Feat/ppdsc 2037 Add "The Times" and "The Sun" fonts && include them in theme checker
  .circleci/config.yml
  .gitignore
  .storybook/fetch-external-fonts.js
  .storybook/preview-head.html
  package.json
  src/theme-checker/themes/tnl-theme/fonts.json
Labels: ready for review, feature

#335 docs(PPDSC-2287): Grid layout documentation
  site/components/component-api/types.ts
  site/components/illustrations/components/grid-layout/anatomy.tsx
  site/components/illustrations/components/grid-layout/options/max-width.tsx
  site/components/illustrations/components/grid-layout/options/offset.tsx
  site/components/illustrations/components/grid-layout/options/order.tsx
  site/components/illustrations/components/grid-layout/options/row-column-gap.tsx
  site/components/illustrations/components/grid-layout/options/span.tsx
  site/components/illustrations/components/grid-layout/usage/do-01.tsx
  site/components/illustrations/components/grid-layout/usage/dont-01.tsx
  site/components/sidebar/sidebar-navigation.tsx
  site/components/text-section/content-text.tsx
  site/components/text-section/types.ts
  site/pages/components/grid-layout.tsx
  site/templates/template-sections/accessibility-section.tsx
  site/templates/template-sections/common-section.tsx
  src/grid-layout/__tests__/stories/common.tsx
  src/grid-layout/__tests__/stories/grid-layout.stories.tsx
  src/grid-layout/__tests__/stories/the-times.tsx
Labels: docs, ready for review

#339 docs(PPDSC-2303): Compliance and related sections changes
  site/pages/components/accordion.tsx
  site/pages/components/banner.tsx
  site/pages/components/block.tsx
  site/pages/components/button.tsx
  site/pages/components/checkbox.tsx
  site/pages/components/divider.tsx
  site/pages/components/drawer.tsx
  site/pages/components/fieldset.tsx
  site/pages/components/form.tsx
  site/pages/components/inline-message.tsx
  site/pages/components/menu.tsx
  site/pages/components/modal.tsx
  site/pages/components/popover.tsx
  site/pages/components/radio-button.tsx
  site/pages/components/select.tsx
  site/pages/components/share-bar.tsx
  site/pages/components/structured-list.tsx
  site/pages/components/tabs.tsx
  site/pages/components/text-field.tsx
  site/pages/components/toast.tsx
  site/pages/components/tooltip.tsx
  site/pages/components/visibility.tsx
Labels: docs, ready for review

#330 chore(PPDSC-2329): codemod link component
  lib/codemod/.eslintignore
  lib/codemod/README.md
  lib/codemod/src/cli.js
  lib/codemod/src/transforms/__tests__/update-linkinline/actual-link-alias.js
  lib/codemod/src/transforms/__tests__/update-linkinline/actual-link-next.js
  lib/codemod/src/transforms/__tests__/update-linkinline/actual.js
  lib/codemod/src/transforms/__tests__/update-linkinline/expected-link-alias.js
  lib/codemod/src/transforms/__tests__/update-linkinline/expected-link-next.js
  lib/codemod/src/transforms/__tests__/update-linkinline/expected.js
  lib/codemod/src/transforms/__tests__/update-linkinline/update-linkinline.test.js
  lib/codemod/src/transforms/__tests__/update-linkstandalone/actual.js
  lib/codemod/src/transforms/__tests__/update-linkstandalone/expected.js
  lib/codemod/src/transforms/__tests__/update-linkstandalone/update-linkstandalone.test.js
  lib/codemod/src/transforms/update-linkinline.js
  lib/codemod/src/transforms/update-linkstandalone.js
  lib/codemod/src/utils/component-utils.js
Labels: ready for review, feature

#336 docs(PPDSC-2297): NewsKit homepage update - banners, explore and more
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/feature-card/feature-card.tsx
  site/components/feature-card/types.ts
  site/components/homepage/explore/explore.tsx
  site/components/homepage/explore/index.ts
  site/components/homepage/index.ts
  site/components/homepage/keep-in-touch/index.ts
  site/components/homepage/keep-in-touch/keep-in-touch.tsx
  site/components/homepage/supported-brands/index.ts
  site/components/homepage/supported-brands/supported-brands.tsx
  site/components/illustrations/brands/barrons.tsx
  site/components/illustrations/brands/index.ts
  site/components/illustrations/brands/mansion-global.tsx
  site/components/illustrations/brands/marketwatch.tsx
  site/components/illustrations/brands/sun.tsx
  site/components/illustrations/brands/talk-radio.tsx
  site/components/illustrations/brands/talk-sport.tsx
  site/components/illustrations/brands/talk-tv.tsx
  site/components/illustrations/brands/times-travel.tsx
  site/components/illustrations/brands/times.tsx
  site/components/illustrations/brands/virgin.tsx
  site/components/illustrations/brands/wsj.tsx
  site/components/illustrations/landing-page/explore-components.tsx
  site/components/illustrations/landing-page/explore-foundations.tsx
  site/components/illustrations/landing-page/explore-patterns.tsx
  site/components/illustrations/landing-page/github.tsx
  site/components/illustrations/landing-page/index.ts
  site/components/illustrations/landing-page/medium.tsx
  site/components/illustrations/landing-page/storybook.tsx
  site/components/index-cards.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/table/__tests__/__snapshots__/table.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  site/components/tools/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/pages/index-new.tsx
  site/public/static/landing/feature-card-banner.svg
  site/public/static/landing/feature-card-contribute-old.svg
  site/public/static/landing/feature-card-contribute.svg
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  site/theme/typography-presets.json
Labels: docs, ready for review

#342 docs(PPDSC-2291): Component defaults documentation
  site/components/illustrations/components/hero-component-defaults-illustration.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/theme/theming/component-defaults.mdx
  site/pages/theme/theming/component-defaults.tsx
  site/routes.ts
Labels: docs, ready for review

#341 fix(PPDSC-2302): remove dev deps from package.json
  package.json
  scripts/build-package-json.js
Labels: fix, ready for review

#346 fix(PPDSC-2266): remove typo in video player styling
  src/video-player/__tests__/__snapshots__/video-player.test.tsx.snap
  src/video-player/styled.tsx
Labels: fix, ready for review

#337 docs(PPDSC-2332): search on doc site
  cypress/site/functional/search.spec.js
  package.json
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/icons/__tests__/__snapshots__/icons.test.tsx.snap
  site/components/icons/icon-filled-search.tsx
  site/components/icons/index.tsx
  site/components/search/__tests__/__snapshots__/search.test.ts.snap
  site/components/search/__tests__/search.test.ts
  site/components/search/index.ts
  site/components/search/search.tsx
  site/components/site-header.tsx
  site/jest-config/style-mock.js
  site/jest.config.js
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  yarn.lock
Labels: docs, ready for review

#351 fix(PPDSC-2392): revert utilityButton020 typography preset
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/site-header.tsx
  site/components/table/__tests__/__snapshots__/table.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  site/components/tools/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/typography-presets.json
Labels: fix, docs

#348 docs(PPDSC-2263): Switch documentation
  site/components/illustrations/components/switch/anatomy.tsx
  site/components/illustrations/components/switch/behaviours/checked-vs-unchecked.tsx
  site/components/illustrations/components/switch/behaviours/clickable-area.tsx
  site/components/illustrations/components/switch/behaviours/focusable-area.tsx
  site/components/illustrations/components/switch/behaviours/label-overflow-wrap.tsx
  site/components/illustrations/components/switch/hero.tsx
  site/components/illustrations/components/switch/options/feedback.tsx
  site/components/illustrations/components/switch/options/label.tsx
  site/components/illustrations/components/switch/options/size.tsx
  site/components/illustrations/components/switch/options/thumb-and-track-size-and-icons.tsx
  site/components/illustrations/components/switch/states/base.tsx
  site/components/illustrations/components/switch/states/checked-disabled.tsx
  site/components/illustrations/components/switch/states/checked-focus-hover.tsx
  site/components/illustrations/components/switch/states/checked-focus.tsx
  site/components/illustrations/components/switch/states/checked-hover.tsx
  site/components/illustrations/components/switch/states/checked.tsx
  site/components/illustrations/components/switch/states/disabled.tsx
  site/components/illustrations/components/switch/states/focus-hover.tsx
  site/components/illustrations/components/switch/states/focus.tsx
  site/components/illustrations/components/switch/states/hover.tsx
  site/components/illustrations/components/switch/usage/do-1.tsx
  site/components/illustrations/components/switch/usage/do-2.tsx
  site/components/illustrations/components/switch/usage/dont-1.tsx
  site/components/illustrations/components/switch/usage/dont-2.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/switch.tsx
  site/routes.ts
  site/templates/template-sections/__tests__/__snapshots__/accessibility-section.test.tsx.snap
  site/templates/template-sections/accessibility-section.tsx
  site/templates/template-sections/states-section.tsx
Labels: docs, ready for review

#355 docs(PPDSC-2394): update readme
  README_COMPONENTS.md
Labels: docs, ready for review
