Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-10, with the labels that each got.

#389 chore(PPDSC-2136): add accessibility tests for newskit dark theme
  cypress/components/accessibility.spec.ts
  e2e/index.tsx
  e2e/tests.tsx
  src/banner/__tests__/banner.stories.tsx
  src/block/__tests__/block.stories.tsx
Labels: ready for review, feature

#392 feat(PPDSC-2405): export withOwnTheme
  src/__tests__/__snapshots__/index.test.ts.snap
  src/utils/index.ts
Labels: ready for review, feature

#390 feat(PPDSC-2384): implement design feedback to search modal
  site/components/search/__tests__/__snapshots__/new-start-screen.test.ts.snap
  site/components/search/new-start-screen.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/typography-presets.json
Labels: ready for review, feature

#397 chore(PPDSC-2415): chore/ppdsc/2415-new logo added
  site/components/illustrations/brands/talk-radio.tsx
Labels: ready for review

#393 docs(PPDSC-2345): Scroll documentation
  site/components/illustrations/components/scroll-illustration.tsx
  site/components/illustrations/components/scroll/anatomy.tsx
  site/components/illustrations/components/scroll/behaviours/overlays.tsx
  site/components/illustrations/components/scroll/options/control-visibility.tsx
  site/components/illustrations/components/scroll/options/orientation.tsx
  site/components/illustrations/components/scroll/options/scroll-bar-visibility.tsx
  site/components/illustrations/components/scroll/options/scroll-snap-alignment.tsx
  site/components/illustrations/components/scroll/options/scroll-step-distance.tsx
  site/components/illustrations/components/scroll/usage/do-01.tsx
  site/components/illustrations/components/scroll/usage/do-02.tsx
  site/pages/components/scroll.mdx
  site/pages/components/scroll.tsx
  site/routes.ts
Labels: docs, ready for review

#395 docs(PPDSC-2439): add utilities and deprecated sections to storybook
  .storybook/preview.js
  cypress/components/audio-player.spec.js
  cypress/components/use-media-query.spec.js
  e2e/tests.tsx
  scripts/generate-a11y-tests.js
  src/aspect-ratio/__tests__/aspect-ratio.stories.tsx
  src/audio-player/__tests__/audio-player.stories.tsx
  src/screen-reader-only/__tests__/screen-reader-only.stories.tsx
  src/share-bar/__tests__/share-bar.stories.tsx
  src/test/storybook-comps.tsx
  src/text-input/__tests__/text-input.stories.tsx
  src/utils/hooks/use-media-query/__tests__/use-media-query.stories.tsx
  src/volume-control/__tests__/volume-control.stories.tsx
Labels: ready for review, feature

#401 Chore/ppdse 2462 release fix with local storage
  cypress/fixtures/consent-request.json
  cypress/fixtures/consent/local-storage/_sp_local_state.json
  cypress/fixtures/consent/local-storage/_sp_non_keyed_local_state.json
  cypress/fixtures/consent/local-storage/_sp_user_consent_5623.json
  cypress/fixtures/consent/stubs/meta.json
  cypress/fixtures/consent/stubs/pv-data.json
  cypress/fixtures/consent/stubs/site-data.json
  cypress/site/functional/header-navigation.spec.js
  cypress/site/functional/playground.spec.js
  cypress/site/functional/search.spec.js
  cypress/support/commands.js
Labels: ready for review

#396 docs(PPDSC-2444): update flag component scenarios + layout updates
  .storybook/preview.js
  src/flag/__tests__/flag.stories.tsx
  src/storybook-pages/welcome.tsx
  src/test/storybook-comps.tsx
Labels: ready for review, feature

#403 docs(PPDSC-2427): draft release notes
  site/utils/release-notes/__tests__/functions.test.tsx
  site/utils/release-notes/functions.ts
  site/utils/release-notes/types.ts
  src/__tests__/__snapshots__/index.test.ts.snap
  src/index.ts
Labels: docs, ready for review

#384 Feat/ppdsc 2415 omlet script
  .eslintignore
  lib/omlet/.gitignore
  lib/omlet/README.md
  lib/omlet/index.ts
  lib/omlet/package.json
  lib/omlet/yarn.lock
  yarn.lock
Labels: ready for review, feature

#408 feat(PPDSC-2421): Background color beyond scroll
  site/pages/_app.tsx
Labels: fix

#406 fix(PPDSC-2432): fix release notes code formatting
  site/components/code.tsx
  site/components/release-notes/__tests__/__snapshots__/release-notes.test.tsx.snap
  site/components/release-notes/__tests__/release-notes.test.tsx
  site/components/release-notes/release-notes.tsx
  site/utils/release-notes/__tests__/functions.test.tsx
  site/utils/release-notes/functions.ts
Labels: fix, ready for review

#394 feat(PPDSC-2246): add character count component
  src/__tests__/__snapshots__/index.test.ts.snap
  src/character-count/__tests__/__snapshots__/character-count.test.tsx.snap
  src/character-count/__tests__/character-count.stories.tsx
  src/character-count/__tests__/character-count.test.tsx
  src/character-count/character-count.tsx
  src/character-count/defaults.ts
  src/character-count/index.ts
  src/character-count/style-presets.ts
  src/character-count/styled.tsx
  src/character-count/types.ts
  src/form/__tests__/form.test.tsx
  src/form/context.ts
  src/form/form-entry.tsx
  src/form/form-input.tsx
  src/index.ts
  src/test/test-utils.tsx
  src/text-field/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#407 docs(PPDSC-2446): update Block component storybook scenarios
  src/block/__tests__/block.stories.tsx
  src/test/storybook-comps.tsx
Labels: docs, ready for review

#404 feat(PPDSC-2448): export hooks
  .storybook/preview.js
  cypress/components/use-media-query.spec.js
  site/helpers/use-media-query.tsx
  site/pages/components/utils/hooks.mdx
  site/pages/theme/foundation/motion.tsx
  site/public/static/examples/hooks/use-controlled.tsx
  site/public/static/examples/hooks/use-intersection.tsx
  site/public/static/examples/hooks/use-keypress.tsx
  site/public/static/examples/hooks/use-resize-observer.tsx
  src/__tests__/__snapshots__/index.test.ts.snap
  src/index.ts
  src/screen-reader-only/__tests__/screen-reader-only.stories.tsx
  src/utils/hooks/__tests__/use-controlled.stories.tsx
  src/utils/hooks/__tests__/use-intersection.stories.tsx
  src/utils/hooks/__tests__/use-keypress.stories.tsx
  src/utils/hooks/__tests__/use-resize-observer.stories.tsx
  src/utils/hooks/use-media-query/__tests__/use-breakpoint-key.stories.tsx
  src/utils/hooks/use-media-query/__tests__/use-media-query-object.stories.tsx
  src/utils/hooks/use-media-query/__tests__/use-media-query-object.test.tsx
  src/utils/hooks/use-media-query/__tests__/use-media-query.stories.tsx
  src/utils/hooks/use-media-query/__tests__/use-media-query.test.tsx
  src/utils/hooks/use-media-query/index.tsx
  src/utils/hooks/use-media-query/use-media-query-object.tsx
  src/utils/hooks/use-media-query/use-media-query.tsx
  src/utils/index.ts
Labels: ready for review, feature

#402 docs(PPDSC-2381): Tag documentation
  cypress/site/functional/section-navigation.spec.js
  site/components/illustrations/components/tag/anatomy.tsx
  site/components/illustrations/components/tag/behaviours/fixed-and-full-width.tsx
  site/components/illustrations/components/tag/hero.tsx
  site/components/illustrations/components/tag/options/icons.tsx
  site/components/illustrations/components/tag/options/lable.tsx
  site/components/illustrations/components/tag/options/size.tsx
  site/components/illustrations/components/tag/states/active.tsx
  site/components/illustrations/components/tag/states/base.tsx
  site/components/illustrations/components/tag/states/focus.tsx
  site/components/illustrations/components/tag/states/hover.tsx
  site/components/illustrations/components/tag/usage/do-01.tsx
  site/components/illustrations/components/tag/usage/do-02.tsx
  site/components/illustrations/components/tag/usage/do-03.tsx
  site/components/illustrations/components/tag/usage/dont-01.tsx
  site/components/illustrations/components/tag/usage/dont-02.tsx
  site/pages/components/tag.mdx
  site/pages/components/tag.tsx
  site/routes.ts
Labels: docs, ready for review

#414 docs(PPDSC-2417): add theme switch to mobile menu
  site/components/layout.tsx
  site/components/menu-collapsible/menu-collapsible.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/__tests__/sidebar.test.tsx
  site/components/sidebar/sidebar.tsx
  site/components/sidebar/styled.tsx
  site/pages/components/drawer.tsx
  src/base-switch/base-switch.tsx
  src/drawer/styled.ts
Labels: docs, ready for review

#411 docs/ppdsc 2445 updated divider stories
  src/divider/__tests__/divider.stories.tsx
Labels: docs, ready for review

#416 feat(PPDSC-2330): re-orgnise codemod
  lib/codemod/.eslintignore
  lib/codemod/README.md
  lib/codemod/src/cli.js
  lib/codemod/src/v6.0.0/__tests__/emotion-icons/actual.js
  lib/codemod/src/v6.0.0/__tests__/emotion-icons/emotion-icons.test.js
  lib/codemod/src/v6.0.0/__tests__/emotion-icons/expected.js
  lib/codemod/src/v6.0.0/__tests__/enums-to-union/actual.js
  lib/codemod/src/v6.0.0/__tests__/enums-to-union/enum-to-union.test.js
  lib/codemod/src/v6.0.0/__tests__/enums-to-union/expected.js
  lib/codemod/src/v6.0.0/__tests__/remove-redundant-marker-ul/actual.jsx
  lib/codemod/src/v6.0.0/__tests__/remove-redundant-marker-ul/expected.jsx
  lib/codemod/src/v6.0.0/__tests__/remove-redundant-marker-ul/remove-redundant-marker-ul.test.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/actual-link-alias.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/actual-link-next.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/actual.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/expected-link-alias.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/expected-link-next.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/expected.js
  lib/codemod/src/v6.0.0/__tests__/update-linkinline/update-linkinline.test.js
  lib/codemod/src/v6.0.0/__tests__/update-linkstandalone/actual.js
  lib/codemod/src/v6.0.0/__tests__/update-linkstandalone/expected.js
  lib/codemod/src/v6.0.0/__tests__/update-linkstandalone/update-linkstandalone.test.js
  lib/codemod/src/v6.0.0/__tests__/update-list-item-marker-ul-value.js/actual.js
  lib/codemod/src/v6.0.0/__tests__/update-list-item-marker-ul-value.js/expected.js
  lib/codemod/src/v6.0.0/__tests__/update-list-item-marker-ul-value.js/update-list-item-marker-ul-value.test.js
  lib/codemod/src/v6.0.0/__tests__/update-token/actual.js
  lib/codemod/src/v6.0.0/__tests__/update-token/expected.js
  lib/codemod/src/v6.0.0/__tests__/update-token/update-token.test.js
  lib/codemod/src/v6.0.0/__tests__/utils.js
  lib/codemod/src/v6.0.0/emotion-icons.js
  lib/codemod/src/v6.0.0/enum-to-union.js
  lib/codemod/src/v6.0.0/remove-redundant-marker-ul.js
  lib/codemod/src/v6.0.0/update-linkinline.js
  lib/codemod/src/v6.0.0/update-linkstandalone.js
  lib/codemod/src/v6.0.0/update-list-item-marker-ul-value.js
  lib/codemod/src/v6.0.0/update-token.js
Labels: ready for review, feature

#410 fix(PPDSC-2431): make sure visual test tests right behaviour
  src/popover/__tests__/popover.stories.tsx
Labels: fix, ready for review

#370 feat(PPDSC-2281): update utilities section in components overview page
  cypress/site/functional/accessibility.spec.js
  cypress/site/functional/sidebar.spec.js
  package.json
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/__tests__/sidebar-navigation.test.tsx
  site/components/sidebar/sidebar-navigation.tsx
  site/components/site-header.tsx
  site/pages/components/overview.tsx
  site/pages/getting-started/overview.tsx
  site/pages/patterns/overview.tsx
  site/pages/theme/overview.tsx
  site/routes.ts
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  site/utils/__tests__/get-route-object.test.ts
  site/utils/get-feature-card.ts
  site/utils/get-route-object.ts
  yarn.lock
Labels: ready for review, feature

#427 ci(PPDSC-2471): update DOCKER_TAG to enable deploys from main
  .circleci/config.yml
Labels: ready for review, task

#428 fix(PPDSC-2488): fix failing cypress tests
  cypress/site/visual/darktheme-snapshots.spec.js
  cypress/site/visual/fullpage-snapshots.spec.js
Labels: fix, ready for review

#424 fix(PPDSC-2494): fix grid-layout areas with no space
  src/grid-layout/__tests__/utils.test.tsx
  src/grid-layout/utils.ts
Labels: fix, ready for review

#432 ci(PPDSC-2471): update DOCKER_TAG in eks_flux_deploy
  .circleci/config.yml
Labels: ready for review, task

#423 Fix/ppdsc 2479 code sandbox broken
  scripts/build-package-json.js
  site/components/playground/code-example.tsx
  site/global.d.ts
Labels: fix, ready for review

#435 ci(PPDSC-2471): release website with every merge to main
  .circleci/config.yml
Labels: ready for review, task

#433 fix(PPDSC-2503): stable eyes-cypress version
  cypress/site/visual/darktheme-snapshots.spec.js
  package.json
  yarn.lock
Labels: fix, ready for review

#422 feat(PPDSC-2472): improve components tracking part 1
  .circleci/config.yml
  .storybook/preview.js
  src/accordion/__tests__/accordion.test.tsx
  src/accordion/accordion.tsx
  src/accordion/types.ts
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/instrumentation/types.ts
  src/select/__tests__/select.test.tsx
  src/select/select.tsx
  src/select/types.ts
  src/selection-list/__tests__/selection-list.test.tsx
  src/selection-list/selection-list-option.tsx
  src/selection-list/types.ts
  src/slider/__tests__/slider.test.tsx
  src/slider/slider.tsx
  src/slider/types.ts
  src/test/test-utils.tsx
Labels: ready for review, feature

#436 fix(PPDSC-2502): Double logical props on stack children
  site/components/homepage/hero/hero-interactive-elements.tsx
  src/stack/__tests__/stack.stories.tsx
  src/stack/stack.tsx
Labels: fix, ready for review

#437 fix(PPDSC-2473): next screen styles
  cypress/site/functional/search.spec.js
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/search/__tests__/__snapshots__/search.test.ts.snap
  site/components/search/search.tsx
Labels: fix, ready for review

#440 fix(PPDSC-2513): add ignore regions to tabs tests
  src/tabs/__tests__/tabs.stories.tsx
Labels: fix, ready for review

#420 docs(PPDSC-2346): Grid cell documentation
  site/components/illustrations/components/grid-cell/anatomy.tsx
  site/components/illustrations/components/grid-cell/behaviours/max-width.tsx
  site/components/illustrations/components/grid-cell/behaviours/nested-grids.tsx
  site/components/illustrations/components/grid-cell/celloptions/offset.tsx
  site/components/illustrations/components/grid-cell/celloptions/order.tsx
  site/components/illustrations/components/grid-cell/celloptions/span.tsx
  site/components/illustrations/components/grid-cell/celloptions/visibility.tsx
  site/components/illustrations/components/grid-cell/gridoptions/breakpoints.tsx
  site/components/illustrations/components/grid-cell/gridoptions/gutter-width.tsx
  site/components/illustrations/components/grid-cell/gridoptions/margin-width.tsx
  site/components/illustrations/components/grid-cell/gridoptions/max-width.tsx
  site/components/illustrations/components/grid-cell/hero.tsx
  site/components/illustrations/components/grid-cell/usage/do-01.tsx
  site/components/illustrations/components/grid-cell/usage/dont-01.tsx
  site/components/illustrations/components/grid-cell/usage/dont-02.tsx
  site/pages/components/grid.mdx
  site/pages/components/grid.tsx
  site/routes.ts
  site/templates/template-sections/interactive-demo-section.tsx
  site/templates/template-sections/options-section.tsx
  site/templates/template-sections/types.ts
Labels: docs, ready for review

#438 docs/PPDSC-1663-add-deprecated-section
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/aspect-ratio.mdx
  site/pages/components/overview.tsx
  site/pages/components/share-bar.tsx
  site/routes.ts
  src/audio-player/audio-player.tsx
Labels: docs, ready for review

#425 docs(PPDSC-2342): added tracking to the navigation and sections clicks
  site/components/layout.tsx
  site/components/link/link.tsx
  site/components/menu-collapsible/menu-collapsible.tsx
  site/components/sidebar/sidebar-navigation.tsx
  site/components/site-footer.tsx
  site/components/site-header.tsx
  site/pages/_app.tsx
  src/menu/__tests__/menu.test.tsx
  src/menu/menu-item.tsx
  src/menu/types.ts
Labels: ready for review, feature

#443 docs/ppdse 2340 update space page
  site/components/illustrations/theme/spacing/block.tsx
  site/components/illustrations/theme/spacing/margin-block-end.tsx
  site/components/illustrations/theme/spacing/margin-block-start.tsx
  site/components/illustrations/theme/spacing/margin-block.tsx
  site/components/illustrations/theme/spacing/margin-inline-end.tsx
  site/components/illustrations/theme/spacing/margin-inline-start.tsx
  site/components/illustrations/theme/spacing/margin-inline.tsx
  site/components/illustrations/theme/spacing/overview.tsx
  site/components/illustrations/theme/spacing/padding-block-end.tsx
  site/components/illustrations/theme/spacing/padding-block-start.tsx
  site/components/illustrations/theme/spacing/padding-block.tsx
  site/components/illustrations/theme/spacing/padding-inline-end.tsx
  site/components/illustrations/theme/spacing/padding-inline-start.tsx
  site/components/illustrations/theme/spacing/padding-inline.tsx
  site/components/illustrations/theme/spacing/space-inline.tsx
  site/components/illustrations/theme/spacing/space-inset.tsx
  site/components/illustrations/theme/spacing/space-stack.tsx
  site/components/illustrations/theme/spacing/stack.tsx
  site/pages/theme/foundation/spacing.tsx
Labels: docs, ready for review

#441 fix(PPDSC-2524): ignore regions for newskit version
  cypress/site/visual/fullpage-snapshots.spec.js
  src/storybook-pages/welcome.stories.tsx
Labels: fix, ready for review
