Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-07, with the labels that each got.

#246 feat(PPDSC-2220): improve main branch protection in ci
  .circleci/config.yml
Labels: ready for review, feature

#249 fix(PPDSC-2164): assistive text
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/form.test.tsx
  src/form/context.ts
  src/form/form-input.tsx
Labels: fix

#241 docs(PPDSC-2188): Patterns gender and names pages
  site/components/illustrations/patterns/forms/gender/hero.tsx
  site/components/illustrations/patterns/forms/names/error-state.tsx
  site/components/illustrations/patterns/forms/names/hero.tsx
  site/components/illustrations/patterns/forms/names/how-to-ask.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/patterns/forms/gender.tsx
  site/pages/patterns/forms/names.tsx
  site/routes.ts
Labels: docs, ready for review

#255 feat(PPDSC-2249): drop concurrency limit for components
  applitools.components.config.js
Labels: feature

#245 feat(PPDSC-2119): floating element motion
  src/base-floating-element/base-floating-element.tsx
  src/base-floating-element/styled.tsx
  src/base-floating-element/types.ts
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/__tests__/popover.stories.tsx
  src/popover/__tests__/popover.test.tsx
  src/popover/defaults.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/tooltip/__tests__/tooltip.stories.tsx
  src/tooltip/__tests__/tooltip.test.tsx
  src/tooltip/defaults.ts
Labels: feature

#258 feat(PPDSC-2226): functionality to dismiss popover
  src/popover/__tests__/popover.stories.tsx
  src/popover/__tests__/popover.test.tsx
  src/popover/popover.tsx
  src/popover/types.ts
Labels: feature

#242 fix(PPDSC-2193): added auto reverse unset to cssfunc
  src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
  src/utils/__tests__/base.test.ts
  src/utils/style/utils.ts
Labels: fix, ready for review

#250 ci(PPDSC-2084): Updating circleci/slack and bringing back all messages on failures
  .circleci/config.yml
Labels: ready for review

#259 Revert "chore(PPDSC-000): Testing with Pancho DEV enviroment and PROD issue"
  .circleci/config.yml
  site/pages/index.tsx
  src/audio-player/__tests__/audio-player.stories.tsx
Labels: ready for review

#244 docs(PPDSC-2189): Patterns passwords and payment pages
  site/components/illustrations/patterns/forms/passwords/error-state.tsx
  site/components/illustrations/patterns/forms/passwords/hero.tsx
  site/components/illustrations/patterns/forms/passwords/how-to-ask.tsx
  site/components/illustrations/patterns/forms/payment/hero.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/patterns/forms/passwords.tsx
  site/pages/patterns/forms/payment.tsx
  site/routes.ts
Labels: docs, ready for review

#248 feat(PPDSC-2218): added Scroll storybook scenario
  src/scroll/__tests__/scroll.stories.tsx
Labels: ready for review, ready for design review

#268 fix(PPDSC-2254): update audio file used in tests
  cypress/components/audio-player-composable.spec.js
  cypress/fixtures/podcasts.json
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/audio-player/__tests__/audio-player.stories.tsx
  src/audio-player/__tests__/audio-player.test.tsx
  src/audio-player/__tests__/auto-play-audio-player.stories.tsx
  src/theme-checker/scenarios.tsx
  static/audio-player-song.mp3
Labels: fix

#235 feat(PPDSC-2180): theme switch added to storybook
  .storybook/preview-head.html
  .storybook/preview.js
  e2e/tests.tsx
  src/accordion/__tests__/accordion.stories.tsx
  src/aspect-ratio/__tests__/aspect-ratio.stories.tsx
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/components/time-display/style-presets.ts
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/audio-player/__tests__/audio-player.stories.tsx
  src/audio-player/style-presets.ts
  src/banner/__tests__/banner.stories.tsx
  src/block/__tests__/block.stories.tsx
  src/button/__tests__/button.stories.tsx
  src/card/__tests__/card.stories.tsx
  src/checkbox/__tests__/checkbox.stories.tsx
  src/drawer/__tests__/drawer-layouts.stories.tsx
  src/drawer/__tests__/drawer.stories.tsx
  src/flag/__tests__/flag.stories.tsx
  src/form/__tests__/form-input.stories.tsx
  src/form/__tests__/form.stories.tsx
  src/grid-layout/__tests__/stories/grid-layout.stories.tsx
  src/headline/__tests__/headline.stories.tsx
  src/icon-button/__tests__/icon-button.stories.tsx
  src/icons/__tests__/icons.stories.tsx
  src/inline-message/__tests__/inline-message.stories.tsx
  src/link/__tests__/link.stories.tsx
  src/menu/__tests__/menu.stories.tsx
  src/modal/__tests__/modal-layouts.stories.tsx
  src/modal/__tests__/modal.stories.tsx
  src/ordered-list/__tests__/ordered-list.stories.tsx
  src/radio-button/__tests__/radio-button.stories.tsx
  src/select/__tests__/select.stories.tsx
  src/stack-child/__tests__/stack-child.stories.tsx
  src/switch/__tests__/helpers.tsx
  src/switch/__tests__/switch.stories.tsx
  src/tabs/__tests__/tabs.stories.tsx
  src/tag/__tests__/tag.stories.tsx
  src/test/storybook-comps.tsx
  src/test/theme-select-object.ts
  src/text-block/__tests__/text-block.stories.tsx
  src/text-field/__tests__/text-field.stories.tsx
  src/theme-checker/__tests__/theme-checker.stories.tsx
  src/theme-checker/styled.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/creator.ts
  src/theme/newskit-dark.ts
  src/toast/__tests__/toast.stories.tsx
  src/tooltip/__tests__/tooltip.stories.tsx
  src/typography/__tests__/heading.stories.tsx
  src/typography/__tests__/paragraph.stories.tsx
  src/typography/__tests__/presets-cropping.stories.tsx
  src/video-player/defaults.ts
  src/video-player/style-presets.ts
Labels: ready for review, feature

#247 chore(PPDSC-2170): Follow-up ticket for Audio Player v2 - Volume Control
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/mute-button.tsx
  src/audio-player-composable/components/volume-control/style-presets.ts
  src/audio-player-composable/components/volume-control/styled.ts
  src/audio-player-composable/components/volume-control/types.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/audio-player-composable/types.ts
  src/slider/__tests__/slider.stories.tsx
  src/slider/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: enhancement, ready for review

#257 fix(PPDSC-2216): add aria-required to form-input-components
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/form/form-input.tsx
Labels: fix, ready for review

#267 docs(PPDSC-2190): Patterns telephone number and input components pages
  site/components/illustrations/patterns/forms/input-components/checkbox/checkbox.tsx
  site/components/illustrations/patterns/forms/input-components/combo-box/combo-box.tsx
  site/components/illustrations/patterns/forms/input-components/hero.tsx
  site/components/illustrations/patterns/forms/input-components/newskit-component/checkbox.tsx
  site/components/illustrations/patterns/forms/input-components/newskit-component/radio-button.tsx
  site/components/illustrations/patterns/forms/input-components/newskit-component/select.tsx
  site/components/illustrations/patterns/forms/input-components/newskit-component/text-field.tsx
  site/components/illustrations/patterns/forms/input-components/radio-group/considerations.tsx
  site/components/illustrations/patterns/forms/input-components/select/select.tsx
  site/components/illustrations/patterns/forms/input-components/text-field/considerations.tsx
  site/components/illustrations/patterns/forms/telephone-number/error-state.tsx
  site/components/illustrations/patterns/forms/telephone-number/hero.tsx
  site/components/illustrations/patterns/forms/telephone-number/how-to-ask.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/patterns/forms/input-components.tsx
  site/pages/patterns/forms/telephone-number.tsx
  site/routes.ts
Labels: docs, ready for review

#277 fix(PPDSC-2277): CircleCI not sending message on pipeline failures
  .circleci/config.yml
Labels: fix, ready for review

#271 docs(PPDSC-2250): Fix for broken links in site
  site/pages/getting-started/design/design-overview.tsx
  site/pages/index.tsx
Labels: docs, ready for review

#273 docs(PPDSC-2224): Fix for PR navigation URL
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/illustrations/theme/hero-outlines-illustration.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/sidebar-navigation.tsx
  site/components/site-header.tsx
  site/routes.ts
Labels: docs, ready for review

#290 Feat/ppdsc 2114 audio player playback speed control 5
  .storybook/preview.js
  docs/scripts.md
  scripts/generate-icons/used-icons-list.json
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/playback-speed-control/defaults.ts
  src/audio-player-composable/components/playback-speed-control/index.ts
  src/audio-player-composable/components/playback-speed-control/playback-speed-control.tsx
  src/audio-player-composable/components/playback-speed-control/playback-speed-list.tsx
  src/audio-player-composable/components/playback-speed-control/types.ts
  src/audio-player-composable/components/playback-speed-control/utils.ts
  src/audio-player-composable/components/seek-bar/style-presets.ts
  src/audio-player-composable/components/volume-control/mute-button.tsx
  src/audio-player-composable/components/volume-control/style-presets.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/base-floating-element/base-floating-element.tsx
  src/base-floating-element/styled.tsx
  src/base-floating-element/types.ts
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/__tests__/popover.test.tsx
  src/select/select.tsx
  src/select/utils.ts
  src/selection-list/selection-list-option.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/utils/check-breakpoint-prop.ts
Labels: feature

#291 feat(PPDSC-2273): add pr and job urls to applitools batch name
  .circleci/config.yml
Labels: feature

#292 docs(PPDSC-2268): Accordion documentation
  site/components/illustrations/components/accordion/anatomy.tsx
  site/components/illustrations/components/accordion/behaviours/allexpandedonload.tsx
  site/components/illustrations/components/accordion/behaviours/collapseexpand.tsx
  site/components/illustrations/components/accordion/behaviours/firstexpandedonload.tsx
  site/components/illustrations/components/accordion/behaviours/singleexpanded.tsx
  site/components/illustrations/components/accordion/hero.tsx
  site/components/illustrations/components/accordion/options/heading.tsx
  site/components/illustrations/components/accordion/options/icon.tsx
  site/components/illustrations/components/accordion/options/singlegroup.tsx
  site/components/illustrations/components/accordion/states/base.tsx
  site/components/illustrations/components/accordion/states/disabled.tsx
  site/components/illustrations/components/accordion/states/focus.tsx
  site/components/illustrations/components/accordion/states/hover.tsx
  site/components/illustrations/components/accordion/usage/do01.tsx
  site/components/illustrations/components/accordion/usage/do02.tsx
  site/components/illustrations/components/accordion/usage/dont01.tsx
  site/components/illustrations/components/accordion/usage/dont02.tsx
  site/components/section-introduction/section-introduction.tsx
  site/components/section-introduction/types.ts
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/accordion.tsx
  site/routes.ts
  site/templates/template-sections/__tests__/__snapshots__/seo-section.test.tsx.snap
  site/templates/template-sections/common-section.tsx
  site/templates/template-sections/seo-section.tsx
Labels: docs, ready for review

#303 feat(PPDSC-2307) switch consistency in defaults
  src/switch/__tests__/__snapshots__/switch.test.tsx.snap
  src/switch/defaults.ts
  src/switch/styled.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#293 feat(PPDSC-2214): add emotion as peer dep
  .circleci/config.yml
  package.json
  site/pages/getting-started/code/engineering-quickstart.tsx
Labels: ready for review, breaking change

#311 feat(PPDSC-2311): temporarily skip aborted tests
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
Labels: feature

#294 chore(PPDSC-2171): add forward red to components part 1
  src/assistive-text/assistive-text.tsx
  src/audio-player-composable/components/forward-button/forward-button.tsx
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/replay-button/replay-button.tsx
  src/audio-player-composable/components/seek-bar/seek-bar.tsx
  src/audio-player-composable/components/skip-next-button/skip-next-button.tsx
  src/audio-player-composable/components/skip-previous-button/skip-previous-button.tsx
  src/audio-player-composable/components/time-display/time-display.tsx
  src/audio-player-composable/components/volume-control/mute-button.tsx
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/block/block.tsx
  src/byline/byline.tsx
  src/caption/caption.tsx
  src/date-time/date-time.tsx
  src/divider/divider.tsx
  src/drawer/drawer.tsx
  src/fieldset/fieldset.tsx
  src/grid-layout/grid-layout.tsx
  src/headline/headline.tsx
  src/icon-button/__tests__/icon-button.test.tsx
  src/icon-button/icon-button.tsx
  src/image/image.tsx
  src/slider/slider.tsx
  src/stack/stack.tsx
  src/stack/types.ts
  src/text-block/text-block.tsx
  src/toast/toast.tsx
Labels: ready for review, breaking change

#296 fix(PPDSC-2241): add stylepresets to dialog header
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/dialog/styled.tsx
  src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
  src/drawer/defaults.ts
  src/drawer/style-presets.ts
  src/modal/__tests__/__snapshots__/modal.test.tsx.snap
  src/modal/defaults.ts
  src/modal/style-presets.ts
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: fix, ready for review

#305 docs(PPDSC-2267): Popover documentation
  site/components/illustrations/components/popover/anatomy.tsx
  site/components/illustrations/components/popover/behaviours/flip.tsx
  site/components/illustrations/components/popover/behaviours/focus.tsx
  site/components/illustrations/components/popover/behaviours/shift.tsx
  site/components/illustrations/components/popover/behaviours/transition.tsx
  site/components/illustrations/components/popover/behaviours/triggering-and-closing.tsx
  site/components/illustrations/components/popover/hero.tsx
  site/components/illustrations/components/popover/options/close-position.tsx
  site/components/illustrations/components/popover/options/distance.tsx
  site/components/illustrations/components/popover/options/placement.tsx
  site/components/illustrations/components/popover/options/pointer.tsx
  site/components/illustrations/components/popover/options/size.tsx
  site/components/illustrations/components/popover/usage/do1.tsx
  site/components/illustrations/components/popover/usage/do2.tsx
  site/components/illustrations/components/popover/usage/do3.tsx
  site/components/illustrations/components/popover/usage/dont1.tsx
  site/components/illustrations/components/popover/usage/dont2.tsx
  site/components/illustrations/components/popover/usage/dont3.tsx
  site/components/illustrations/components/popover/usage/dont4.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/popover.tsx
  site/routes.ts
Labels: docs, ready for review

#312 feat(PPDSC-2256): update dropcap logical props and presets
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/typography-presets.json
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/typography-presets.ts
  src/typography/__tests__/__snapshots__/paragraph.test.tsx.snap
  src/typography/__tests__/paragraph.stories.tsx
  src/typography/__tests__/paragraph.test.tsx
  src/typography/paragraph/defaults.ts
  src/typography/paragraph/paragraph.tsx
Labels: ready for review, feature

#315 feat(PPDSC-2215): add forwardRef to components part 2
  src/audio-player-composable/components/playback-speed-control/playback-speed-control.tsx
  src/banner/banner-internal.tsx
  src/banner/banner.tsx
  src/base-floating-element/base-floating-element.tsx
  src/dialog/base-dialog-function.tsx
  src/label/label.tsx
  src/modal/modal.tsx
  src/ordered-list/ordered-list.tsx
  src/popover/popover.tsx
  src/standfirst/standfirst.tsx
  src/tabs/tabs.tsx
  src/tag/tag.tsx
  src/title-bar/title-bar.tsx
  src/tooltip/tooltip.tsx
  src/unordered-list/unordered-list.tsx
Labels: ready for review, feature, breaking change

#316 chore(PPDSC-2229): update storybook container styles
  .storybook/preview.js
Labels: ready for review

#313 docs(PPDSC-2269): Tooltip documentation
  site/components/illustrations/components/button/usage/do3.tsx
  site/components/illustrations/components/tooltip/anatomy.tsx
  site/components/illustrations/components/tooltip/behaviours/flip.tsx
  site/components/illustrations/components/tooltip/behaviours/shift.tsx
  site/components/illustrations/components/tooltip/behaviours/transition.tsx
  site/components/illustrations/components/tooltip/behaviours/triggering-and-closing.tsx
  site/components/illustrations/components/tooltip/hero.tsx
  site/components/illustrations/components/tooltip/options/distance.tsx
  site/components/illustrations/components/tooltip/options/placement.tsx
  site/components/illustrations/components/tooltip/options/pointer.tsx
  site/components/illustrations/components/tooltip/options/size.tsx
  site/components/illustrations/components/tooltip/usage/do1.tsx
  site/components/illustrations/components/tooltip/usage/do2.tsx
  site/components/illustrations/components/tooltip/usage/do3.tsx
  site/components/illustrations/components/tooltip/usage/do4.tsx
  site/components/illustrations/components/tooltip/usage/dont1.tsx
  site/components/illustrations/components/tooltip/usage/dont2.tsx
  site/components/illustrations/components/tooltip/usage/dont3.tsx
  site/components/illustrations/components/tooltip/usage/dont4.tsx
  site/components/illustrations/components/tooltip/usage/dont5.tsx
  site/components/media-list/types.ts
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/button.tsx
  site/pages/components/tooltip.tsx
  site/routes.ts
  site/templates/template-sections/__tests__/__snapshots__/accessibility-section.test.tsx.snap
  site/templates/template-sections/accessibility-section.tsx
  site/templates/template-sections/usage-section.tsx
Labels: docs, ready for review
