Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-04, with the labels that each got.

#142 feat(PPDSC-2051): AudioPlayer composable: Implemented forward and replay scales
  scripts/generate-icons/icons-full-list.js
  scripts/generate-icons/used-icons-list.json
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/forward-button/forward-button.tsx
  src/audio-player-composable/types.ts
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/icons/__tests__/__snapshots__/custom-icons.test.tsx.snap
  src/icons/filled/custom/icon-filled-forward-10.tsx
  src/icons/filled/custom/icon-filled-forward-15.tsx
  src/icons/filled/custom/icon-filled-forward-20.tsx
  src/icons/filled/custom/icon-filled-forward-25.tsx
  src/icons/filled/custom/icon-filled-forward-30.tsx
  src/icons/filled/custom/icon-filled-forward-5.tsx
  src/icons/filled/custom/icon-filled-replay-10.tsx
  src/icons/filled/custom/icon-filled-replay-15.tsx
  src/icons/filled/custom/icon-filled-replay-20.tsx
  src/icons/filled/custom/icon-filled-replay-25.tsx
  src/icons/filled/custom/icon-filled-replay-30.tsx
  src/icons/filled/custom/icon-filled-replay-5.tsx
  src/icons/filled/custom/index.ts
  src/icons/outlined/custom/icon-outlined-forward-10.tsx
  src/icons/outlined/custom/icon-outlined-forward-15.tsx
  src/icons/outlined/custom/icon-outlined-forward-20.tsx
  src/icons/outlined/custom/icon-outlined-forward-25.tsx
  src/icons/outlined/custom/icon-outlined-forward-30.tsx
  src/icons/outlined/custom/icon-outlined-forward-5.tsx
  src/icons/outlined/custom/icon-outlined-replay-10.tsx
  src/icons/outlined/custom/icon-outlined-replay-15.tsx
  src/icons/outlined/custom/icon-outlined-replay-20.tsx
  src/icons/outlined/custom/icon-outlined-replay-25.tsx
  src/icons/outlined/custom/icon-outlined-replay-30.tsx
  src/icons/outlined/custom/icon-outlined-replay-5.tsx
  src/icons/outlined/custom/index.ts
  src/icons/to-newskit-icon.tsx
Labels: ready for review

#141 feat(PPDSC-2050): audio player scenarios
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/theme-checker/scenarios.tsx
Labels: ready for review, feature

#140 feat(PPDSC-2052): keyboard shortcuts next prev
  cypress/components/audio-player-composable.spec.js
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/forward-button/forward-button.tsx
  src/audio-player-composable/components/forward-button/index.ts
  src/audio-player-composable/components/forward-button/types.ts
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/play-pause-button/types.ts
  src/audio-player-composable/components/replay-button/index.ts
  src/audio-player-composable/components/replay-button/replay-button.tsx
  src/audio-player-composable/components/replay-button/types.ts
  src/audio-player-composable/components/seek-bar/seek-bar.tsx
  src/audio-player-composable/components/seek-bar/types.ts
  src/audio-player-composable/components/skip-next-button/defaults.ts
  src/audio-player-composable/components/skip-next-button/index.ts
  src/audio-player-composable/components/skip-next-button/skip-next-button.tsx
  src/audio-player-composable/components/skip-next-button/types.ts
  src/audio-player-composable/components/skip-next/index.ts
  src/audio-player-composable/components/skip-previous-button/defaults.ts
  src/audio-player-composable/components/skip-previous-button/index.ts
  src/audio-player-composable/components/skip-previous-button/skip-previous-button.tsx
  src/audio-player-composable/components/skip-previous-button/types.ts
  src/audio-player-composable/components/skip-previous/index.ts
  src/audio-player-composable/components/time-display/time-display.tsx
  src/audio-player-composable/components/time-display/types.ts
  src/audio-player-composable/components/time-display/utils.tsx
  src/audio-player-composable/components/types.ts
  src/audio-player-composable/context.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/audio-player-composable/utils.ts
  src/dialog/base-dialog-tests.tsx
  src/theme-checker/scenarios.tsx
  src/utils/hooks/__tests__/use-keypress.test.ts
  src/utils/hooks/use-keypress.ts
Labels: ready for review, feature

#126 feat(PPDSC-2007): New Release flow and Gitflow to GitHub flow
  .circleci/config.yml
  Makefile
  README.md
  docs/scripts.md
  package.json
  scripts/release.sh
Labels: ready for review, feature

#153 chore(PPDSC-2007): GitFlow to GitHub Flow: Fixing version parameter drill
  .circleci/config.yml
  Makefile
Labels: ready for review

#157 Chore/ppdsc 2007 rolling back package.json version
  package.json
Labels: ready for review

#152 docs(PPDSC-1903): Select page
  site/components/illustrations/components/select/anatomy.tsx
  site/components/illustrations/components/select/behaviours/checked-vs-unchecked.tsx
  site/components/illustrations/components/select/behaviours/validation-icon.tsx
  site/components/illustrations/components/select/behaviours/validation.tsx
  site/components/illustrations/components/select/options/custom-selected-display.tsx
  site/components/illustrations/components/select/options/end-enhancer.tsx
  site/components/illustrations/components/select/options/min-height.tsx
  site/components/illustrations/components/select/options/mobile.tsx
  site/components/illustrations/components/select/options/placeholder-text.tsx
  site/components/illustrations/components/select/options/pre-selected-option.tsx
  site/components/illustrations/components/select/options/size.tsx
  site/components/illustrations/components/select/options/start-enhancer.tsx
  site/components/illustrations/components/select/options/width.tsx
  site/components/illustrations/components/select/select-illustration.tsx
  site/components/illustrations/components/select/states/base.tsx
  site/components/illustrations/components/select/states/disabled.tsx
  site/components/illustrations/components/select/states/focus.tsx
  site/components/illustrations/components/select/states/hover.tsx
  site/components/illustrations/components/select/states/invalid-focus.tsx
  site/components/illustrations/components/select/states/invalid-hover.tsx
  site/components/illustrations/components/select/states/invalid.tsx
  site/components/illustrations/components/select/states/read-only.tsx
  site/components/illustrations/components/select/states/selected.tsx
  site/components/illustrations/components/select/states/valid-focus.tsx
  site/components/illustrations/components/select/states/valid-hover.tsx
  site/components/illustrations/components/select/states/valid.tsx
  site/components/illustrations/components/select/usage/do-1.tsx
  site/components/illustrations/components/select/usage/do-2.tsx
  site/components/illustrations/components/select/usage/dont-1.tsx
  site/components/illustrations/components/select/usage/dont-2.tsx
  site/components/illustrations/components/select/usage/dont-3.tsx
  site/components/illustrations/components/select/usage/dont-4.tsx
  site/pages/components/select.tsx
Labels: docs, ready for review

#158 fix(PPDSR-2081): fix broken link in site
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/feature-card/__tests__/feature-card.test.tsx
  site/components/feature-card/feature-card.tsx
  site/components/feature-card/styled.ts
  site/components/feature-card/types.ts
  site/components/index-cards.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/pages/components/select.tsx
  site/pages/components/title-bar.mdx
  site/pages/theme/presets/style-presets.tsx
Labels: fix, ready for review

#171 fix(PPDSC-2105): remove unnecessarily disabled a11y rules in cmp tests
  src/banner/__tests__/banner.stories.tsx
  src/drawer/__tests__/drawer-layouts.stories.tsx
  src/form/__tests__/form-input.stories.tsx
  src/menu/__tests__/menu.stories.tsx
  src/modal/__tests__/modal-layouts.stories.tsx
  src/modal/__tests__/modal.stories.tsx
  src/structured-list/__tests__/structured-list.stories.tsx
  src/toast/__tests__/toast.stories.tsx
Labels: fix

#170 fix(PPDSC-2104): increase next version to >12.1.1
  package.json
  yarn.lock
Labels: fix

#167 chore(PPDSC-2079): update axe-core and fix any errors
  package.json
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/scroll/__tests__/__snapshots__/scroll.test.tsx.snap
  src/scroll/scroll.tsx
  src/slider/__tests__/__snapshots__/slider.test.tsx.snap
  src/slider/__tests__/__snapshots__/stateful-slider.test.tsx.snap
  src/slider/slider.tsx
  src/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
  src/volume-control/__tests__/__snapshots__/volume-control.test.tsx.snap
  yarn.lock
Labels: fix, ready for review

#173 fix(PPDSC-2108): handle different browser zoom level in scroll tests
  cypress/components/scroll.spec.js
  src/scroll/scroll.tsx
  src/scroll/utils.ts
Labels: fix, ready for review

#172 fix(PPDSC-2106): correct minimum supported node version
  .circleci/config.yml
  README.md
  package.json
Labels: fix, ready for review

#160 feat(PPDSC-2054): add feedback element and transition preset to slider, checkbox & radio button
  package.json
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/components/seek-bar/defaults.ts
  src/audio-player/__tests__/__snapshots__/audio-player.test.tsx.snap
  src/base-switch/base-switch.tsx
  src/base-switch/styled.tsx
  src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
  src/checkbox/__tests__/checkbox.test.tsx
  src/checkbox/defaults.ts
  src/checkbox/style-presets.ts
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/radio-button/defaults.ts
  src/radio-button/style-presets.ts
  src/slider/__tests__/__snapshots__/slider.test.tsx.snap
  src/slider/__tests__/__snapshots__/stateful-slider.test.tsx.snap
  src/slider/__tests__/slider.stories.tsx
  src/slider/defaults.ts
  src/slider/slider.tsx
  src/slider/styled.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/__tests__/style-presets.test.ts
  src/theme/presets/style-presets.ts
  src/theme/presets/transition-presets.ts
  src/theme/presets/types.ts
  src/utils/__tests__/__snapshots__/style-preset.test.tsx.snap
  src/utils/__tests__/style-preset.test.tsx
  src/utils/focus-visible.ts
  src/utils/style/style-preset.ts
  src/volume-control/__tests__/__snapshots__/volume-control.test.tsx.snap
  yarn.lock
Labels: ready for review, feature

#148 docs(PPDSC-2006): shrink all title and desc containers for docs
  site/components/content-structure/__tests__/__snapshots__/content-structure.test.tsx.snap
  site/components/content-structure/content-base.tsx
  site/components/content-structure/index.tsx
  site/components/content-structure/types.tsx
  site/components/step/__tests__/__snapshots__/step.test.tsx.snap
  site/components/step/step.tsx
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  site/components/tabs-with-table/tabs-with-table.tsx
  site/pages/about/contact-us.tsx
  site/pages/about/contribute.tsx
  site/pages/about/roadmap.tsx
  site/pages/getting-started/code/engineering-quickstart.tsx
  site/pages/getting-started/code/instrumentation.tsx
  site/pages/getting-started/design/design-quickstart.tsx
  site/pages/help/terms-and-conditions.tsx
  site/pages/theme/borders.tsx
  site/pages/theme/colours.tsx
  site/pages/theme/fonts.tsx
  site/pages/theme/iconography.tsx
  site/pages/theme/motion.tsx
  site/pages/theme/presets/style-presets.tsx
  site/pages/theme/presets/transition-presets.tsx
  site/pages/theme/presets/typography-presets.tsx
  site/pages/theme/sizing.tsx
  site/pages/theme/spacing.tsx
Labels: ready for review, feature

#180 fix(PPDSC-2134): make BaseSwitch data-testid overridable
  src/base-switch/base-switch.tsx
  src/checkbox/__tests__/checkbox.test.tsx
Labels: fix, ready for review
