Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-06, with the labels that each got.

#209 feat(PPDSC-1985): logical props 5/6
  site/pages/components/scroll.mdx
  site/pages/components/select.tsx
  site/pages/components/slider.mdx
  site/pages/components/stack.mdx
  site/pages/components/standfirst.mdx
  site/pages/components/structured-list.tsx
  src/headline/headline.tsx
  src/scroll/__tests__/__snapshots__/scroll.test.tsx.snap
  src/scroll/__tests__/scroll.stories.tsx
  src/scroll/__tests__/scroll.test.tsx
  src/scroll/styled.ts
  src/scroll/types.ts
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/__tests__/select.test.tsx
  src/select/styled.tsx
  src/select/types.ts
  src/slider/__tests__/__snapshots__/slider.test.tsx.snap
  src/slider/__tests__/slider.stories.tsx
  src/slider/__tests__/slider.test.tsx
  src/slider/slider.tsx
  src/slider/types.ts
  src/stack-child/__tests__/__snapshots__/stack-child.test.tsx.snap
  src/stack-child/__tests__/stack-child.stories.tsx
  src/stack-child/__tests__/stack-child.test.tsx
  src/stack-child/types.ts
  src/stack/stack.tsx
  src/stack/styled.ts
  src/standfirst/__tests__/__snapshots__/standfirst.test.tsx.snap
  src/standfirst/__tests__/standfirst.stories.tsx
  src/standfirst/__tests__/standfirst.test.tsx
  src/standfirst/standfirst.tsx
  src/standfirst/types.ts
  src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap
  src/structured-list/__tests__/structured-list.stories.tsx
  src/structured-list/__tests__/structured-list.test.tsx
  src/structured-list/defaults.ts
  src/structured-list/styled.tsx
  src/structured-list/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/utils/logical-properties.ts
Labels: ready for review, feature

#223 feat(PPDSC-2175): layout props 7/7
  site/pages/components/unordered-list.mdx
  src/typography/__tests__/__snapshots__/heading.test.tsx.snap
  src/typography/__tests__/__snapshots__/paragraph.test.tsx.snap
  src/typography/__tests__/heading.stories.tsx
  src/typography/__tests__/heading.test.tsx
  src/typography/__tests__/paragraph.stories.tsx
  src/typography/__tests__/paragraph.test.tsx
  src/typography/heading/heading.tsx
  src/typography/paragraph/paragraph.tsx
  src/unordered-list/__tests__/__snapshots__/unordered-list.test.tsx.snap
  src/unordered-list/__tests__/unordered-list.stories.tsx
  src/unordered-list/__tests__/unordered-list.test.tsx
  src/unordered-list/styled.ts
  src/unordered-list/types.ts
  src/unordered-list/unordered-list.tsx
  src/video-player/__tests__/__snapshots__/video-player.test.tsx.snap
  src/video-player/__tests__/video-player-overrides.stories.tsx
  src/video-player/__tests__/video-player.test.tsx
  src/video-player/styled.tsx
  src/video-player/types.ts
Labels: ready for review, feature

#217 feat(PPDSC-2118): tooltip pointer
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/tooltip/__tests__/tooltip.stories.tsx
  src/tooltip/__tests__/tooltip.test.tsx
  src/tooltip/defaults.ts
  src/tooltip/style-presets.ts
  src/tooltip/styled.tsx
  src/tooltip/tooltip.tsx
  src/tooltip/types.ts
  src/tooltip/utils.ts
Labels: ready for review, feature

#221 fix(PPDSC-2203): handling non text children in Paragraph
  src/typography/__tests__/__snapshots__/paragraph.test.tsx.snap
  src/typography/__tests__/paragraph.stories.tsx
  src/typography/__tests__/paragraph.test.tsx
  src/typography/paragraph/paragraph.tsx
Labels: fix, ready for review

#218 docs(PPDSC-2172): Patterns index and overview pages
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/content-structure/types.tsx
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/feature-card/feature-card.tsx
  site/components/illustrations/patterns/forms/overview/hero.tsx
  site/components/illustrations/patterns/forms/overview/why-use/best-practice.tsx
  site/components/illustrations/patterns/forms/overview/why-use/consistency.tsx
  site/components/illustrations/patterns/forms/overview/why-use/ease-of-use.tsx
  site/components/illustrations/patterns/hero.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/menu-collapsible/menu-collapsible.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/sidebar-navigation.tsx
  site/components/sidebar/types.ts
  site/components/site-header.tsx
  site/pages/patterns/forms/overview.tsx
  site/pages/patterns/overview.tsx
  site/routes.ts
  site/templates/pattern-page-template/pattern-page-template.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
Labels: docs, ready for review

#227 Fix/ppdsc 2208 newskit not working on iframe REVERT CHANGES
  cypress/site/functional/consent.spec.js
  site/pages/_document.tsx
Labels: ready for review

#216 docs/ppdse 2173 build foundation pages
  site/components/illustrations/theme/gradients/hero.tsx
  site/components/illustrations/theme/opacity/hero.tsx
  site/components/illustrations/theme/overlays/do.tsx
  site/components/illustrations/theme/overlays/dont.tsx
  site/components/illustrations/theme/overlays/hero.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/table/column-map.ts
  site/components/table/column-renderer.tsx
  site/components/table/types.ts
  site/components/tabs-with-table/types.ts
  site/components/theming-values/overlays/swatches.tsx
  site/pages/theme/gradients.tsx
  site/pages/theme/opacity.tsx
  site/pages/theme/overlays.mdx
  site/pages/theme/overlays.tsx
  site/pages/theme/presets/style-presets.tsx
  site/routes.ts
  src/drawer/__tests__/drawer.stories.tsx
Labels: docs, ready for review

#224 feat(PPDSC-2152): single accordion
  scripts/generate-icons/used-icons-list.json
  src/__tests__/__snapshots__/index.test.ts.snap
  src/accordion/__tests__/__snapshots__/accordion.test.tsx.snap
  src/accordion/__tests__/accordion.stories.tsx
  src/accordion/__tests__/accordion.test.tsx
  src/accordion/accordion.tsx
  src/accordion/defaults.ts
  src/accordion/index.ts
  src/accordion/style-presets.ts
  src/accordion/styled.ts
  src/accordion/types.ts
  src/index.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review

#225 docs(PPDSC-2191): Patterns best practice page
  site/components/base-card/__tests__/__snapshots__/base-card.test.tsx.snap
  site/components/base-card/base-card.tsx
  site/components/illustrations/patterns/forms/best-practice/best-practice/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/call-to-actions/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/call-to-actions/visual-treatment.tsx
  site/components/illustrations/patterns/forms/best-practice/hero.tsx
  site/components/illustrations/patterns/forms/best-practice/labels/optional.tsx
  site/components/illustrations/patterns/forms/best-practice/labels/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/progress-abandonment/abandonment.tsx
  site/components/illustrations/patterns/forms/best-practice/progress-abandonment/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/security-captcha/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/structure-layout/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/validation-error-messages/tip.tsx
  site/components/illustrations/patterns/forms/best-practice/validation-error-messages/validation.tsx
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/patterns/forms/best-practice.tsx
  site/routes.ts
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
Labels: docs, ready for review

#208 Feat/ppdsc 2112 audio player v2 volume control
  .storybook/manager.js
  cypress/components/audio-player-composable.spec.js
  src/__tests__/__snapshots__/index.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-functions.ts
  src/audio-player-composable/audio-player-composable.tsx
  src/audio-player-composable/components/audio-element.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/index.ts
  src/audio-player-composable/components/volume-control/mute-button.tsx
  src/audio-player-composable/components/volume-control/style-presets.ts
  src/audio-player-composable/components/volume-control/styled.ts
  src/audio-player-composable/components/volume-control/types.ts
  src/audio-player-composable/components/volume-control/utils.ts
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/audio-player-composable/index.ts
  src/audio-player-composable/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review

#229 fix(PPDSC-2213): Fix for featurecard banner render issue
  cypress/site/functional/accessibility.spec.js
  cypress/site/functional/social.spec.js
  cypress/site/visual/fullpage-snapshots.spec.js
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/button.tsx
  site/pages/components/utils/get-defaults.mdx
  site/pages/theme/foundation/borders.tsx
  site/pages/theme/foundation/breakpoints.tsx
  site/pages/theme/foundation/colours.tsx
  site/pages/theme/foundation/design-tokens.tsx
  site/pages/theme/foundation/fonts.tsx
  site/pages/theme/foundation/gradients.tsx
  site/pages/theme/foundation/iconography.tsx
  site/pages/theme/foundation/motion.tsx
  site/pages/theme/foundation/opacity.tsx
  site/pages/theme/foundation/overlays.tsx
  site/pages/theme/foundation/shadows.tsx
  site/pages/theme/foundation/sizing.tsx
  site/pages/theme/foundation/spacing.tsx
  site/pages/theme/presets/style-presets.tsx
  site/pages/theme/presets/typography-presets.tsx
  site/routes.ts
  site/utils/get-feature-card.ts
Labels: fix, ready for review

#230 fix(PPDSC-2199): docs-ppdse-2199-drawer-correct-state
  src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
  src/drawer/__tests__/drawer.stories.tsx
  src/drawer/__tests__/drawer.test.tsx
  src/drawer/drawer.tsx
  src/drawer/styled.ts
  src/modal/__tests__/__snapshots__/modal.test.tsx.snap
  src/modal/modal.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/utils/__tests__/get-transition-class.test.ts
  src/utils/get-transition-class-name.ts
Labels: fix, ready for review

#233 docs(PPDSC-2186): Patterns address and dob pages
  site/components/illustrations/patterns/forms/address/error-state.tsx
  site/components/illustrations/patterns/forms/address/hero.tsx
  site/components/illustrations/patterns/forms/address/how-to-ask.tsx
  site/components/illustrations/patterns/forms/address/how-to-display.tsx
  site/components/illustrations/patterns/forms/date-of-birth/error-state.tsx
  site/components/illustrations/patterns/forms/date-of-birth/hero.tsx
  site/components/illustrations/patterns/forms/date-of-birth/how-to-ask.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/patterns/forms/address.tsx
  site/pages/patterns/forms/best-practice.tsx
  site/pages/patterns/forms/date-of-birth.tsx
  site/pages/patterns/forms/overview.tsx
  site/routes.ts
  site/templates/template-sections/introduction-section.tsx
  site/utils/styled.tsx
Labels: docs, ready for review

#232 fix(PPDSC-2166): website broken repo links
  site/components/meta/__tests__/__snapshots__/meta.test.tsx.snap
  site/components/meta/__tests__/meta.test.tsx
  site/components/meta/introduce.tsx
  site/pages/components/checkbox.tsx
  site/pages/components/text-field.tsx
Labels: fix, ready for review, Requires design review

#234 feat(PPDSC-2156): accordion group
  src/__tests__/__snapshots__/index.test.ts.snap
  src/accordion/__tests__/__snapshots__/accordion.test.tsx.snap
  src/accordion/__tests__/accordion.stories.tsx
  src/accordion/__tests__/accordion.test.tsx
  src/accordion/accordion-group.tsx
  src/accordion/accordion.tsx
  src/accordion/index.ts
  src/accordion/types.ts
Labels: ready for review, feature

#231 feat(PPDSC-2161): <SelectionList/> component
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/select/style-presets.ts
  src/selection-list/__tests__/__snapshots__/selection-list.test.tsx.snap
  src/selection-list/__tests__/selection-list.stories.tsx
  src/selection-list/__tests__/selection-list.test.tsx
  src/selection-list/defaults.ts
  src/selection-list/index.ts
  src/selection-list/selection-list-option.tsx
  src/selection-list/selection-list.tsx
  src/selection-list/styled.tsx
  src/selection-list/types.ts
  src/selection-list/utils.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/style-presets.ts
  src/utils/hooks/use-keypress.ts
Labels: ready for review, feature

#243 feat(PPDSC-2151): add outline override examples
  src/accordion/__tests__/accordion.stories.tsx
  src/button/__tests__/button.stories.tsx
  src/checkbox/__tests__/checkbox.stories.tsx
  src/icon-button/__tests__/icon-button.stories.tsx
  src/link/__tests__/link.stories.tsx
  src/menu/__tests__/menu.stories.tsx
  src/radio-button/__tests__/radio-button.stories.tsx
  src/select/__tests__/select.stories.tsx
  src/slider/__tests__/slider.stories.tsx
  src/switch/__tests__/switch.stories.tsx
  src/tabs/__tests__/tabs.stories.tsx
  src/tag/__tests__/tag.stories.tsx
  src/text-field/__tests__/text-field.stories.tsx
Labels: ready for review, feature
