Repository newscorp-ghfb/NewsKit, pull requests merged in 2022-12, with the labels that each got.

#503 docs(PPDSC-2474): add overrides storybook themes support
  src/banner/__tests__/banner.stories.tsx
  src/block/__tests__/block.stories.tsx
  src/character-count/__tests__/character-count.stories.tsx
  src/divider/__tests__/divider.stories.tsx
  src/test/theme-select-object.ts
  src/theme-checker/themes/storybook-newskit-dark/colors.json
  src/theme-checker/themes/storybook-newskit-dark/storybook-newskit-dark-theme.ts
  src/theme-checker/themes/storybook-newskit-light/colors.json
  src/theme-checker/themes/storybook-newskit-light/storybook-newskit-light-theme.ts
Labels: docs, ready for design review

#493 feat(PPDSC-2555): SVG Exporter - Export with CSS vars
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/components/svg-previewer/__tests__/expected-file-mock.tsx
  site/components/svg-previewer/__tests__/figma-svg-mock-data.tsx
  site/components/svg-previewer/__tests__/svg-previewer.test.tsx
  site/components/svg-previewer/colors-theme-list.tsx
  site/components/svg-previewer/controls/download-controls.tsx
  site/components/svg-previewer/controls/theme-controls.tsx
  site/components/svg-previewer/controls/types.ts
  site/components/svg-previewer/styled.tsx
  site/components/svg-previewer/svg-previewer.tsx
  site/components/tools/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/components/tools/__tests__/expected-file-mock.tsx
  site/components/tools/__tests__/figma-svg-mock-data.tsx
  site/components/tools/controls/download-controls.tsx
  site/components/tools/styled.tsx
  site/pages/tools/preview-illustration-export.tsx
Labels: ready for review, feature

#497 feat(PPDSC-2597): expose select icon override and onOpen prop
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/pages/components/select.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/__tests__/select.test.tsx
  src/select/defaults.ts
  src/select/select-button.tsx
  src/select/select.tsx
  src/select/styled.tsx
  src/select/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#505 chore(PPDSC-2614): simplify fetching branch name for merge commit
  .circleci/config.yml
  scripts/check-baseline-updates.js
Labels: ready for review

#492 chore(PPDSC-2481): add marketwatch and wsj themes
  .storybook/fetch-external-fonts.js
  .storybook/preview-head.html
  .storybook/preview.js
  src/test/theme-select-object.ts
  src/theme-checker/themes/market-watch-theme/borders.json
  src/theme-checker/themes/market-watch-theme/colors.json
  src/theme-checker/themes/market-watch-theme/fonts.json
  src/theme-checker/themes/market-watch-theme/market-watch-theme.ts
  src/theme-checker/themes/market-watch-theme/overlays.json
  src/theme-checker/themes/market-watch-theme/shadows.json
  src/theme-checker/themes/market-watch-theme/typography-presets.json
  src/theme-checker/themes/wsj-theme/borders.json
  src/theme-checker/themes/wsj-theme/colors.json
  src/theme-checker/themes/wsj-theme/fonts.json
  src/theme-checker/themes/wsj-theme/overlays.json
  src/theme-checker/themes/wsj-theme/shadows.json
  src/theme-checker/themes/wsj-theme/typography-presets.json
  src/theme-checker/themes/wsj-theme/wsj-theme.ts
Labels: docs, ready for review

#510 fix(PPDSC-2591): select virtualized list measure correct size
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/__tests__/select.test.tsx
  src/select/use-virtualized-list.tsx
Labels: fix, ready for review

#509 docs(PPDSC-2495): update Button component storybook scenarios
  src/button/__tests__/button.stories.tsx
  src/theme-checker/themes/storybook-newskit-dark/colors.json
Labels: docs, ready for review

#512 docs(PPDSC-2600): update Assistive Text component storybook scenarios
  src/assistive-text/__tests__/assistive-text.stories.tsx
Labels: docs, ready for review

#516 docs(PPDSC-2627) updated overrides in doc sites
  site/pages/components/accordion.tsx
  site/pages/components/audio-player.tsx
  site/pages/components/flag.tsx
  site/pages/components/modal.tsx
Labels: bug, docs, ready for review

#511 docs(PPDSC-2557): update Byline component storybook scenarios
  src/byline/__tests__/byline.stories.tsx
Labels: docs, ready for review

#504 feat(PPDSC-2609): submenu overrides and href
  site/components/component-api/common-logical-props.tsx
  site/pages/components/menu.tsx
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/menu/__tests__/menu.stories.tsx
  src/menu/__tests__/menu.test.tsx
  src/menu/context.ts
  src/menu/defaults.ts
  src/menu/menu-item.tsx
  src/menu/menu-sub.tsx
  src/menu/style-presets.ts
  src/menu/styled.tsx
  src/menu/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#502 docs(PPDSC-2595): Use Google Sheets as CMS for Roadmap page
  .gitignore
  package.json
  scripts/build-package-json.js
  site/pages/about/roadmap.tsx
  site/pages/index.tsx
  site/utils/google-sheet/__tests__/utils.test.ts
  site/utils/google-sheet/get-sheets.ts
  site/utils/google-sheet/utils.ts
  yarn.lock
Labels: ready for review

#519 docs(PPDSC-2601): update Accordion component storybook scenarios
  .storybook/preview.js
  site/public/static/1x1-placeholder.png
  src/accordion/__tests__/accordion.stories.tsx
  static/1x1-placeholder.png
Labels: docs, ready for review

#521 docs(PPDSC-2602): update Caption component storybook scenarios
  src/caption/__tests__/caption.stories.tsx
Labels: docs, ready for review

#524 docs(PPDSC-2561) Update titles in Usage section on site to support custom titles
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/usage-card/__tests__/__snapshots__/usage-card.test.tsx.snap
  site/components/usage-card/types.ts
  site/components/usage-card/usage-card.tsx
  site/pages/components/text-area.tsx
  site/public/static/illustrations/components/text-area/usage/do-01.svg
  site/public/static/illustrations/components/text-area/usage/do-02.svg
  site/public/static/illustrations/components/text-area/usage/do-03.svg
  site/public/static/illustrations/components/text-area/usage/do-04.svg
  site/public/static/illustrations/components/text-area/usage/dont-01.svg
  site/public/static/illustrations/components/text-area/usage/dont-02.svg
  site/public/static/illustrations/components/text-area/usage/dont-03.svg
Labels: enhancement, docs, ready for review, task

#525 fix(PPDSC-2596): flexbox issue in Safari
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  src/popover/__tests__/popover.stories.tsx
  src/switch/__tests__/__snapshots__/switch.test.tsx.snap
  src/switch/styled.tsx
  src/switch/switch.tsx
Labels: fix, ready for review

#520 fix(PPDSC-2631): fix select panel position
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  src/form/__tests__/form.test.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/select-panel.tsx
  src/select/select.tsx
  src/select/styled.tsx
Labels: fix, ready for review

#530 chore(PPDSC-2518): upgrade to next.js 13
  cypress/site/functional/404.spec.js
  cypress/site/functional/playground.spec.js
  cypress/site/functional/search.spec.js
  cypress/site/functional/table-of-content.spec.js
  package.json
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/homepage/hero/hero.tsx
  site/components/homepage/whats-new/whats-new.tsx
  site/components/link/link.tsx
  site/components/media-list/media-list.tsx
  site/components/menu-collapsible/menu-collapsible.tsx
  site/components/search/doc-search-hit.tsx
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/sidebar-navigation.test.tsx
  site/components/sidebar/sidebar-navigation.tsx
  site/components/site-header.tsx
  site/components/table-of-contents/__tests__/__snapshots__/table-of-contents.test.tsx.snap
  site/pages/components/byline.mdx
  site/pages/components/consent-settings-link.mdx
  site/pages/components/experimentation-web.mdx
  site/pages/index.tsx
  site/templates/foundation-page-template/__tests__/foundation-page-template.test.tsx
  site/templates/pattern-page-template/__tests__/pattern-page-template.test.tsx
  yarn.lock
Labels: ready for review

#527 fix(PPDSC-2634): select panel zindex
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/pages/components/select.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.test.tsx
  src/select/defaults.ts
  src/select/select-panel.tsx
  src/select/select.tsx
  src/select/styled.tsx
  src/select/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: fix
