Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-02, with the labels that each got.

#592 chore(PPDSC-2412): audio player styling changes
  lib/codemod/README.md
  lib/codemod/package.json
  lib/codemod/src/utils/__tests__/add-prop.test.js
  lib/codemod/src/utils/add-prop.js
  lib/codemod/src/v7.0.0/__tests__/all-default-styles.test.js
  lib/codemod/src/v7.0.0/__tests__/audio-player-default-styles.test.js
  lib/codemod/src/v7.0.0/all-default-styles.js
  lib/codemod/src/v7.0.0/audio-player-default-styles.js
  lib/codemod/yarn.lock
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
  src/audio-player-composable/components/time-display/defaults.ts
  src/audio-player-composable/components/volume-control/defaults.ts
  src/audio-player-composable/components/volume-control/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review

#583 fix(PPDSC-2717): fix aria-labelledby on select panel
  site/pages/components/select.tsx
  src/form/form-input.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/__tests__/select.test.tsx
  src/select/select.tsx
  src/select/types.ts
Labels: fix, ready for review

#611 docs(PPDSC-2325): set tracking default object
  site/utils/instrumentation.ts
Labels: docs

#613 feat(PPDSC-2782): changing dividerInverse color
  README.md
  src/divider/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature, breaking change

#596 fix(PPDSC-2611): fix pipeline
  .circleci/config.yml
  scripts/__tests__/check-baseline-updates.test.js
  scripts/check-baseline-updates.js
Labels: fix, ready for review

#603 ci(PPDSC-2771): circleci work for dev k8s to s3 migration
  .circleci/config.yml
  .gitignore
  Makefile
  dev.tfvars
  outputs.tf
  provider.tf
  terraform/s3/README.md
  terraform/s3/dev-newskit/dev.tfvars
  terraform/s3/dev-newskit/outputs.tf
  terraform/s3/dev-newskit/provider.tf
  terraform/s3/dev-newskit/remote-state/main.tf
  terraform/s3/dev-newskit/s3.tf
  terraform/s3/dev-newskit/variables.tf
  terraform/s3/prod-newskit/outputs.tf
  terraform/s3/prod-newskit/prod.tfvars
  terraform/s3/prod-newskit/provider.tf
  terraform/s3/prod-newskit/remote-state/main.tf
  terraform/s3/prod-newskit/s3.tf
  terraform/s3/prod-newskit/staging.tfvars
  terraform/s3/prod-newskit/variables.tf
Labels: ready for review

#606 chore(PPDSC-2723): update Slider component defaults
  lib/codemod/README.md
  src/slider/__tests__/__snapshots__/slider.test.tsx.snap
  src/slider/__tests__/__snapshots__/stateful-slider.test.tsx.snap
  src/slider/defaults.ts
  src/slider/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/volume-control/__tests__/__snapshots__/volume-control.test.tsx.snap
Labels: ready for review, breaking change, task

#599 Docs/ppdsc 2551 content update feedback and status
  site/pages/components/banner.tsx
  site/pages/components/inline-message.tsx
  site/pages/components/toast.tsx
  site/pages/components/tooltip.tsx
  site/templates/template-sections/__tests__/__snapshots__/usage-section.test.tsx.snap
  site/templates/template-sections/usage-section.tsx
Labels: docs, ready for review

#615 Feat/ppdsc 2726 change card default
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  src/card/__tests__/__snapshots__/card.test.tsx.snap
  src/card/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature, breaking change

#617 chore(PPDSC-2774): update Popover component defaults
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, breaking change, task

#595 docs(PPDSC-2710): update image component storybook scenarios
  .storybook/manager-head.html
  .storybook/preview.js
  src/image/__tests__/image.stories.tsx
  static/placeholders-lazy-load/placeholder-01.png
  static/placeholders-lazy-load/placeholder-02.png
  static/placeholders-lazy-load/placeholder-03.png
  static/placeholders-lazy-load/placeholder-04.png
  static/placeholders-lazy-load/placeholder-05.png
  static/placeholders-lazy-load/placeholder-06.png
  static/placeholders-lazy-load/placeholder-07.png
  static/placeholders-lazy-load/placeholder-08.png
  static/placeholders-lazy-load/placeholder-09.png
  static/placeholders-lazy-load/placeholder-10.png
Labels: docs, ready for review

#608 chore(PPDSC-2722): update Select component defaults
  lib/codemod/README.md
  lib/codemod/src/utils/__tests__/add-prop.test.js
  lib/codemod/src/utils/add-prop.js
  lib/codemod/src/v6.0.0/update-list-item-marker-ul-value.js
  lib/codemod/src/v7.0.0/audio-player-play-pause-button.js
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/defaults.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, breaking change, task

#623 fix(PPDSC-2712): circle remote docker has no space left
  .circleci/config.yml
Labels: ready for review

#586 feat(PPDSC-2689): Community Contributions pages
  scripts/component-status.js
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/community/community-index.tsx
  site/pages/components/community/how-to-contribute.tsx
  site/public/static/illustrations/components/community/community-index.svg
  site/public/static/illustrations/components/community/how-to-contribute.svg
  site/routes.ts
Labels: ready for review

#622 Chore/ppdsc 2778 tag default styles
  src/card/__tests__/__snapshots__/card.test.tsx.snap
  src/stack-child/__tests__/__snapshots__/stack-child.test.tsx.snap
  src/tag/__tests__/__snapshots__/tag.test.tsx.snap
  src/tag/style-presets.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, breaking change

#629 Fix/ppdsc 2611 fix 1
  .circleci/config.yml
Labels: fix

#621 chore(PPDSC-2573): storybook - hide docs in modal & drawer stories
  src/drawer/__tests__/drawer-layouts.stories.tsx
  src/drawer/__tests__/drawer.stories.tsx
  src/modal/__tests__/modal-layouts.stories.tsx
  src/modal/__tests__/modal.stories.tsx
Labels: ready for review

#616 feat(PPDSC-2781): update menu defaults
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/menu.tsx
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/menu/__tests__/menu.stories.tsx
  src/menu/__tests__/menu.test.tsx
  src/menu/defaults.ts
  src/menu/menu-item.tsx
  src/menu/menu-sub.tsx
  src/menu/styled.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature, breaking change

#631 docs(PPDSC-1966): remove amp mentions
  site/pages/components/consent.mdx
Labels: docs

#605 chore(PPDSC-2780): chore/ppdse-2780-titlebar-defaults fixed defaults
  site/components/section-introduction/__tests__/__snapshots__/section-introduction.test.ts.snap
  site/components/section-introduction/section-introduction.tsx
  site/pages/components/title-bar.mdx
  site/templates/template-sections/__tests__/__snapshots__/accessibility-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/anatomy-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/behaviors-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/code-examples-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/common-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/compliance-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/interactive-demo-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/options-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/seo-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/states-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/usage-section.test.tsx.snap
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/test/storybook-comps.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/title-bar/__tests__/__snapshots__/title-bar.test.tsx.snap
  src/title-bar/__tests__/title-bar.stories.tsx
  src/title-bar/__tests__/title-bar.test.tsx
  src/title-bar/defaults.ts
  src/title-bar/styled.tsx
  src/title-bar/types.ts
Labels: ready for review, breaking change

#626 fix(PPDSC-2830): fix logo rerendering on home page
  README.md
  site/components/homepage/hero/hero-interactive-elements.tsx
Labels: docs, ready for review

#624 feat(PPDSC-1940): remove Link component
  .gitignore
  site/components/site-footer.tsx
  site/pages/components/heading.mdx
  site/pages/components/icons.mdx
  site/pages/components/link.tsx
  site/pages/components/paragraph.mdx
  site/pages/components/utils/overview.mdx
  site/pages/getting-started/code/testing.mdx
  site/pages/getting-started/design/design-values.mdx
  site/pages/getting-started/design/ways-of-working.mdx
  site/pages/help/faqs.mdx
  site/pages/table-variants.tsx
  site/pages/theme/presets/overview.mdx
  src/__tests__/__snapshots__/index.test.ts.snap
  src/card/__tests__/card.stories.tsx
  src/drawer/__tests__/drawer-e2e.stories.tsx
  src/drawer/__tests__/drawer-layouts.stories.tsx
  src/drawer/__tests__/drawer.stories.tsx
  src/inline-message/__tests__/inline-message.stories.tsx
  src/link/__tests__/link.stories.tsx
  src/link/index.ts
  src/link/link-inline.ts
  src/link/link.tsx
  src/modal/__tests__/modal-layouts.stories.tsx
  src/modal/__tests__/modal.stories.tsx
  src/test/__tests__/test-utils.test.ts
  src/title-bar/__tests__/__snapshots__/title-bar.test.tsx.snap
  src/title-bar/__tests__/title-bar.stories.tsx
  src/title-bar/__tests__/title-bar.test.tsx
  src/toast/__tests__/toast.stories.tsx
  src/unordered-list/__tests__/__snapshots__/unordered-list.test.tsx.snap
  src/unordered-list/__tests__/unordered-list.stories.tsx
  src/unordered-list/__tests__/unordered-list.test.tsx
Labels: ready for review, feature

#638 chore(PPDSC-2732): migrate staging docs from k8s to S3
  .circleci/config.yml
  src/audio-player/__tests__/audio-player.test.tsx
  terraform/s3/README.md
  terraform/s3/dev-newskit/dev.tfvars
  terraform/s3/dev-newskit/outputs.tf
  terraform/s3/dev-newskit/provider.tf
  terraform/s3/dev-newskit/s3.tf
  terraform/s3/dev-newskit/variables.tf
  terraform/s3/prod-newskit/outputs.tf
  terraform/s3/prod-newskit/prod.tfvars
  terraform/s3/prod-newskit/provider.tf
  terraform/s3/prod-newskit/s3.tf
  terraform/s3/prod-newskit/staging.tfvars
  terraform/s3/prod-newskit/variables.tf
Labels: ready for review

#643 fix(PPDSC-1866): handle string line height
  src/utils/__tests__/text-crop.test.ts
  src/utils/text-crop.ts
Labels: fix, ready for review

#644 ci(PPDSC-2746): migrate prod docs from k8s to s3
  .circleci/config.yml
Labels: ready for review

#641 feat(PPDSC-2428): Popover Tooltip AudioPlayer override name
  lib/codemod/src/utils/replace-distance.js
  lib/codemod/src/v7.0.0/__tests__/audio-player-volume-control.test.js
  lib/codemod/src/v7.0.0/__tests__/popover.test.js
  lib/codemod/src/v7.0.0/__tests__/tooltip.test.js
  lib/codemod/src/v7.0.0/audio-player-volume-control.js
  lib/codemod/src/v7.0.0/popover.js
  lib/codemod/src/v7.0.0/tooltip.js
  site/components/homepage/hero/hero-interactive-elements.tsx
  site/pages/components/popover.tsx
  site/pages/components/tooltip.tsx
  site/public/static/illustrations/components/popover/options/offset.svg
  site/public/static/illustrations/components/tooltip/options/offset.svg
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/audio-player-composable/components/volume-control/defaults.ts
  src/base-floating-element/base-floating-element.tsx
  src/base-floating-element/types.ts
  src/base-floating-element/utils.ts
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/__tests__/popover.stories.tsx
  src/popover/__tests__/popover.test.tsx
  src/popover/defaults.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  src/tooltip/__tests__/tooltip.stories.tsx
  src/tooltip/__tests__/tooltip.test.tsx
  src/tooltip/defaults.ts
Labels: ready for review, feature, breaking change

#652 docs(PPDSC-2801): update Label storybook scenarios
  src/label/__tests__/label.stories.tsx
Labels: docs, ready for review

#651 docs(PPDSC-2668): standfirst page
  site/pages/components/standfirst.mdx
  site/pages/components/standfirst.tsx
  site/public/static/illustrations/components/standfirst/01-hero/hero.svg
  site/public/static/illustrations/components/standfirst/02-anatomy/anatomy.svg
  site/public/static/illustrations/components/standfirst/03-options/heading-level.svg
  site/public/static/illustrations/components/standfirst/04-dos-donts/do-01.svg
Labels: docs, ready for review

#639 fix(PPDSC-2829): add inverse focus outline styles
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/templates/foundation-page-template/__tests__/__snapshots__/foundation-page-template.test.tsx.snap
  site/templates/pattern-page-template/__tests__/__snapshots__/pattern-page-template.test.tsx.snap
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/banner/__tests__/__snapshots__/banner.test.tsx.snap
  src/button/style-presets.ts
  src/icon-button/style-presets.ts
  src/link/style-presets.ts
  src/menu/style-presets.ts
  src/tag/style-presets.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/colors.ts
  src/theme/foundations/outlines.ts
  src/theme/newskit-dark.ts
  src/utils/inverse-focus-visible.ts
Labels: fix, ready for review

#649 chore(PPDSC-2837): update TNL font
  .storybook/fetch-external-fonts.js
  .storybook/preview-head.html
  fonts/Roboto-Medium.woff2
  src/theme-checker/themes/tnl-theme/fonts.json
Labels: ready for review, feature

#654 docs(PPDSC-2805): update Ordered list component storybook scenarios
  src/ordered-list/__tests__/ordered-list.stories.tsx
Labels: docs, ready for review

#625 chore(PPDSC-1866): remove crop config
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/search/__tests__/__snapshots__/search.test.ts.snap
  site/components/table/__tests__/__snapshots__/table.test.tsx.snap
  site/pages/theme/theming/creating-a-theme.mdx
  site/public/static/examples/fonts/configuring-text-cropping.tsx
  site/public/static/examples/theming/font-crop-config.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/fonts.json
  src/theme-checker/themes/sun-theme/fonts.json
  src/theme-checker/themes/virgin-theme/fonts.json
  src/theme/foundations/fonts.ts
  src/typography/__tests__/presets-cropping.stories.tsx
  src/utils/__tests__/__snapshots__/typography-preset.test.tsx.snap
  src/utils/__tests__/typography-preset.test.tsx
  src/utils/get-font-props.ts
  src/utils/style/getters.ts
  src/utils/text-crop.ts
Labels: ready for review, breaking change

#658 chore(PPDSC-2832): simplify percy regeneration script
  docs/scripts.md
  scripts/percy_local.sh
  yarn.lock
Labels: ready for review

#659 docs(PPDSC-2807): update Paragraph component storybook scenarios
  .storybook/preview.js
  src/typography/__tests__/paragraph.stories.tsx
Labels: docs, ready for review

#661 docs(PPDSC-2821): update TextBlock component storybook scenarios
  src/text-block/__tests__/text-block.stories.tsx
Labels: docs, ready for review

#663 feat(PPDSC-2838): use new s3 for pr links
  .circleci/config.yml
  scripts/s3-pr-branch-naming.js
  site/pages/components/flag.tsx
  site/pages/components/ordered-list.tsx
  site/pages/components/text-area.tsx
Labels: ready for review, feature

#647 docs(PPDSC-2667) image documentation
  site/pages/components/image.mdx
  site/pages/components/image.tsx
  site/public/static/illustrations/components/image/anatomy.svg
  site/public/static/illustrations/components/image/behaviours/loading.svg
  site/public/static/illustrations/components/image/hero.svg
  site/public/static/illustrations/components/image/options/caption.svg
  site/public/static/illustrations/components/image/options/imagedimensions.svg
  site/public/static/illustrations/components/image/options/placeholdericon.svg
  site/public/static/illustrations/components/image/states/base.svg
  site/public/static/illustrations/components/image/states/loading.svg
  site/public/static/illustrations/components/image/usage/dont-01.svg
  site/routes.ts
Labels: docs, ready for review
