Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-01, with the labels that each got.

#531 fix(PPDSE-2633): fix-ppdse-2633 added noCrop
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  src/base-switch/styled.tsx
  src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
  src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
  src/form/__tests__/__snapshots__/form.test.tsx.snap
  src/radio-button/__tests__/__snapshots__/radio-button.test.tsx.snap
  src/switch/__tests__/__snapshots__/switch.test.tsx.snap
Labels: fix, ready for review

#528 docs(PPDSC-2538) breadcrumbs documentation
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/breadcrumbs.tsx
  site/pages/components/menu.tsx
  site/public/static/illustrations/components/breadcrumbs/anatomy.svg
  site/public/static/illustrations/components/breadcrumbs/behaviours/selected-breadcrumb-item.svg
  site/public/static/illustrations/components/breadcrumbs/hero.svg
  site/public/static/illustrations/components/breadcrumbs/options/separator.svg
  site/public/static/illustrations/components/breadcrumbs/options/size.svg
  site/public/static/illustrations/components/breadcrumbs/states/active.svg
  site/public/static/illustrations/components/breadcrumbs/states/base.svg
  site/public/static/illustrations/components/breadcrumbs/states/focus.svg
  site/public/static/illustrations/components/breadcrumbs/states/hover.svg
  site/public/static/illustrations/components/breadcrumbs/states/selected.svg
  site/public/static/illustrations/components/breadcrumbs/usage/do-01.svg
  site/public/static/illustrations/components/breadcrumbs/usage/do-02.svg
  site/public/static/illustrations/components/breadcrumbs/usage/do-03.svg
  site/public/static/illustrations/components/breadcrumbs/usage/dont-01.svg
  site/public/static/illustrations/components/breadcrumbs/usage/dont-02.svg
  site/public/static/illustrations/components/breadcrumbs/usage/dont-03.svg
  site/public/static/illustrations/components/breadcrumbs/usage/dont-04.svg
  site/public/static/illustrations/components/breadcrumbs/usage/dont-05.svg
  site/public/static/illustrations/components/menu/sub-menu-anatomy.svg
  site/routes.ts
Labels: docs, ready for review

#537 docs(PPDSC-2648): fix hydration error on why newskit page
  site/pages/about/why-use-newskit.tsx
Labels: docs

#518 Feat(PPDSC-2572): uncontrolled sub menu
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/menu/__tests__/menu.stories.tsx
  src/menu/__tests__/menu.test.tsx
  src/menu/context.ts
  src/menu/menu-item.tsx
  src/menu/menu-sub.tsx
  src/menu/menu.tsx
  src/menu/types.ts
  src/menu/utils.ts
Labels: ready for review, feature

#538 chore(PPDSC-2643): add missing unit tests for getSheets
  site/utils/google-sheet/__tests__/get-sheets.test.ts
  site/utils/google-sheet/get-sheets.ts
  src/link/__tests__/utils.test.tsx
  src/link/utils.tsx
  src/test/__tests__/test-utils.test.ts
Labels: ready for review

#536 docs(PPDSC-2325): improve tracking in playground section
  site/components/playground/index.tsx
  site/components/playground/knobs/input-knob.tsx
  site/components/playground/knobs/multichoice-knob.tsx
  site/pages/_document.tsx
  site/routes.ts
Labels: docs, ready for review

#542 docs(PPDSC-2650): react error on components overview
  site/pages/components/overview.tsx
Labels: docs, ready for review

#529 feat(PPDSC-2647): image width & height props
  site/pages/components/image.mdx
  src/image/__tests__/__snapshots__/image.test.tsx.snap
  src/image/__tests__/image.stories.tsx
  src/image/__tests__/image.test.tsx
  src/image/image.tsx
  src/image/types.ts
  src/image/utils.ts
Labels: ready for review, feature

#534 docs(PPDSC-2559): build 404 page
  cypress/site/functional/404.spec.js
  site/components/homepage/hero/styled.ts
  site/components/layout.tsx
  site/pages/404.tsx
  site/public/static/illustrations/404-hero.svg
Labels: docs, ready for review

#544 docs(PPDSC-2653): fix console errors on homepage
  site/components/homepage/hero/hero-interactive-elements.tsx
  site/components/homepage/supported-brands/supported-brands.tsx
  src/accordion/accordion.tsx
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/audio-player-composable/components/volume-control/volume-control.tsx
  src/base-floating-element/base-floating-element.tsx
  src/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
  src/drawer/drawer.tsx
  src/modal/__tests__/__snapshots__/modal.test.tsx.snap
  src/modal/modal.tsx
  src/overlay/__tests__/__snapshots__/overlay.test.tsx.snap
  src/overlay/overlay.tsx
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
Labels: fix, docs, ready for review

#549 chore(PPDSC-1581): upgrade to cypress 12
  .circleci/config.yml
  Makefile
  cypress.components.config.ts
  cypress.docs.config.ts
  cypress.docs.percy.config.ts
  cypress.docs.percy.skip.config.ts
  cypress/components/accessibility.cy.ts
  cypress/components/audio-player-composable.cy.js
  cypress/components/audio-player.cy.js
  cypress/components/auto-play-audio-player.cy.js
  cypress/components/drawer.cy.js
  cypress/components/form.cy.js
  cypress/components/image.cy.js
  cypress/components/scroll.cy.js
  cypress/components/toast.cy.js
  cypress/components/use-media-query.cy.js
  cypress/config/cypress.components.json
  cypress/config/cypress.docs.json
  cypress/config/cypress.docs.percy.json
  cypress/config/cypress.docs.percy.skip.json
  cypress/plugins/files.js
  cypress/site/functional/404.cy.js
  cypress/site/functional/accessibility.cy.js
  cypress/site/functional/consent.cy.js
  cypress/site/functional/header-navigation.cy.js
  cypress/site/functional/playground.cy.js
  cypress/site/functional/search.cy.js
  cypress/site/functional/section-navigation.cy.js
  cypress/site/functional/sidebar.cy.js
  cypress/site/functional/social.cy.js
  cypress/site/functional/storybook-links.cy.js
  cypress/site/functional/table-of-content.cy.js
  cypress/site/percy-skip/empty-snapshot.cy.js
  cypress/site/percy/darktheme-snapshots.cy.js
  cypress/site/percy/empty-snapshot.cy.js
  cypress/site/percy/fullpage-snapshots.cy.js
  cypress/support/e2e.js
  cypress/support/index.js
  package.json
  scripts/generate-a11y-tests.js
  scripts/templates-integration-test/cypress.config.js
  scripts/templates-integration-test/cypress.json
  scripts/templates-integration-test/cypress/e2e/theme-checker.cy.js
  scripts/templates-integration-test/cypress/support/commands.js
  scripts/templates-integration-test/cypress/support/e2e.js
  tsconfig.eslint.json
  yarn.lock
Labels: ready for review

#551 feat(PPDSC-2510): add dismissOnBlur prop to Popover
  site/pages/components/popover.tsx
  src/base-floating-element/base-floating-element.tsx
  src/base-floating-element/types.ts
  src/popover/__tests__/popover.stories.tsx
  src/popover/__tests__/popover.test.tsx
  src/popover/popover.tsx
  src/tooltip/types.ts
Labels: ready for review, feature

#552 docs(PPDSC-2652): fix console errors on components tabs page
  site/components/playground/knobs/input-knob.tsx
  site/components/playground/knobs/multichoice-knob.tsx
  site/components/unpack-content/unpack-content.tsx
  src/tabs/utils.ts
Labels: fix, docs, ready for review

#561 docs(PPDSC-2325): transform event object
  site/pages/_app.tsx
  site/utils/instrumentation.ts
Labels: docs, ready for review

#557 Docs/ppdsc 2552 content updates
  site/components/component-api/common-logical-props.tsx
  site/pages/components/accordion.tsx
  site/pages/components/banner.tsx
  site/pages/components/block.tsx
  site/pages/components/divider.tsx
  site/pages/components/drawer.tsx
  site/pages/components/fieldset.tsx
  site/pages/components/flag.tsx
  site/pages/components/grid-layout.tsx
  site/pages/components/modal.tsx
  site/pages/components/popover.tsx
  site/pages/components/share-bar.tsx
  site/pages/components/structured-list.tsx
  site/pages/components/tooltip.tsx
  site/pages/components/visibility.tsx
Labels: docs, ready for design review

#566 docs(PPDSC-2693): add stylePreset to TextBlock
  site/pages/about/roadmap.tsx
Labels: docs, ready for review

#565 feat(PPDSC-2696): set default padding block to 'space000' for breadCrumbItem
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  src/breadcrumbs/__tests__/breadcrumbs.stories.tsx
  src/breadcrumbs/defaults.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#563 docs(PPDSC-2636): update release notes page
  site/components/release-notes/__tests__/__snapshots__/release-badges.test.tsx.snap
  site/components/release-notes/__tests__/__snapshots__/release-header.test.tsx.snap
  site/components/release-notes/__tests__/__snapshots__/release-notes.test.tsx.snap
  site/components/release-notes/release-badges.tsx
  site/components/release-notes/release-header.tsx
  site/components/release-notes/release-notes.tsx
  site/pages/about/release-notes.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
Labels: docs, ready for review

#567 docs(PPDSC-2660): headline page
  site/pages/components/headline.mdx
  site/pages/components/headline.tsx
  site/public/static/illustrations/components/headline/anatomy.svg
  site/public/static/illustrations/components/headline/hero.svg
  site/public/static/illustrations/components/headline/options/heading-level.svg
  site/public/static/illustrations/components/headline/options/kicker.svg
  site/public/static/illustrations/components/headline/usage/do-01.svg
  site/templates/template-sections/__tests__/__snapshots__/interactive-demo-section.test.tsx.snap
  site/templates/template-sections/interactive-demo-section.tsx
  site/templates/template-sections/options-section.tsx
Labels: docs, ready for review

#553 feat(ppdsc-2658):add styled component name to classname for debugging
  site/next.config.js
Labels: feature

#564 chore(PPDSC-2625): fail build on cms issues
  site/pages/about/roadmap.tsx
  site/pages/index.tsx
  site/utils/google-sheet/__tests__/get-sheets.test.ts
  site/utils/google-sheet/__tests__/utils.test.ts
  site/utils/google-sheet/get-sheets.ts
  site/utils/google-sheet/types.ts
  site/utils/google-sheet/utils.ts
Labels: ready for review

#572 docs(PPDSC-2571): refactor Meta component
  site/components/meta/__tests__/__snapshots__/meta.test.tsx.snap
  site/components/meta/meta.tsx
Labels: docs, ready for review

#576 chore(PPDSC-1580): upgrade to jest 29
  lib/codemod/jest.config.js
  package.json
  scripts/percy_local.sh
  site/components/svg-previewer/__tests__/svg-previewer.test.tsx
  site/jest.config.js
  site/pages/getting-started/code/testing.mdx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player/__tests__/audio-player.test.tsx
  src/icons/__tests__/icons.stories.tsx
  src/jest.config.js
  src/utils/audio-tests.tsx
  yarn.lock
Labels: ready for review

#575 fix(PPDSC-2659): update breadcrumb icon to use margin instead of padding
  site/pages/components/breadcrumbs.tsx
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  src/breadcrumbs/defaults.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: fix, ready for review

#540 fix(PPDSC-2661): add controlled prop to Select
  site/pages/components/select.tsx
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.test.tsx
  src/select/select.tsx
  src/select/types.ts
Labels: fix, ready for review

#578 docs(PPDSC-2664): byline documentation
  site/pages/components/byline.mdx
  site/pages/components/byline.tsx
  site/public/static/illustrations/components/byline/anatomy/anatomy.svg
  site/public/static/illustrations/components/byline/behaviours/responsive.svg
  site/public/static/illustrations/components/byline/options/divider.svg
  site/public/static/illustrations/components/byline/options/job-title.svg
  site/public/static/illustrations/components/byline/options/link.svg
  site/public/static/illustrations/components/byline/options/location.svg
Labels: docs, ready for review

#574 docs(PPDSC-2497): layer & layerOrganizer docs
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/layer.tsx
  site/public/static/illustrations/components/layer-illustration.svg
  site/public/static/illustrations/components/layer/layer-illustration.svg
  site/routes.ts
  site/templates/template-sections/usage-section.tsx
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/style-presets.ts
  src/layer/__tests__/layer.stories.tsx
Labels: docs, ready for review

#573 docs/ppdsc 2616 onboarding new pages
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/sidebar-navigation.tsx
  site/pages/patterns/onboarding/best-practice.tsx
  site/pages/patterns/onboarding/how-to.tsx
  site/pages/patterns/onboarding/overview.tsx
  site/pages/patterns/overview.tsx
  site/public/static/illustrations/patterns/onboarding/best-practice/hero.svg
  site/public/static/illustrations/patterns/onboarding/how-to/choose-components.svg
  site/public/static/illustrations/patterns/onboarding/how-to/document-rules.svg
  site/public/static/illustrations/patterns/onboarding/how-to/hero.svg
  site/public/static/illustrations/patterns/onboarding/how-to/select-appropriate-components.svg
  site/public/static/illustrations/patterns/onboarding/how-to/write-a-scenario.svg
  site/public/static/illustrations/patterns/onboarding/overview/hero.svg
  site/routes.ts
Labels: docs, ready for review

#570 docs(PPDSC-2662): slider page
  cypress/site/functional/storybook-links.cy.js
  site/components/flags/mono-keyboard/mono-keyboard.tsx
  site/components/playground/index.tsx
  site/components/playground/knobs/multichoice-knob.tsx
  site/components/playground/types.ts
  site/pages/components/drawer.tsx
  site/pages/components/headline.tsx
  site/pages/components/modal.tsx
  site/pages/components/slider.mdx
  site/pages/components/slider.tsx
  site/public/static/illustrations/components/slider/anatomy.svg
  site/public/static/illustrations/components/slider/hero.svg
  site/public/static/illustrations/components/slider/options/feedback.svg
  site/public/static/illustrations/components/slider/options/indicator-weight.svg
  site/public/static/illustrations/components/slider/options/label-position.svg
  site/public/static/illustrations/components/slider/options/min-and-max.svg
  site/public/static/illustrations/components/slider/options/minmax-labels.svg
  site/public/static/illustrations/components/slider/options/orientation.svg
  site/public/static/illustrations/components/slider/options/step-distance.svg
  site/public/static/illustrations/components/slider/options/thumb-icon.svg
  site/public/static/illustrations/components/slider/options/thumb-label.svg
  site/public/static/illustrations/components/slider/options/track-weight.svg
  site/public/static/illustrations/components/slider/states/active.svg
  site/public/static/illustrations/components/slider/states/base.svg
  site/public/static/illustrations/components/slider/states/disabled.svg
  site/public/static/illustrations/components/slider/states/focus.svg
  site/public/static/illustrations/components/slider/states/hover.svg
  site/public/static/illustrations/components/slider/thumb-control.svg
  site/public/static/illustrations/components/slider/usage/labels.svg
  site/public/static/illustrations/components/slider/usage/prefix.svg
  site/public/static/illustrations/components/slider/usage/values.svg
  site/templates/component-page-template/__tests__/component-page-template.test.tsx
  site/templates/component-page-template/component-page-basic-template.tsx
  site/templates/component-page-template/component-page-template.tsx
  site/templates/component-page-template/types.ts
  site/templates/template-sections/__tests__/interactive-demo-section.test.tsx
  site/templates/template-sections/interactive-demo-section.tsx
Labels: docs, ready for review

#587 docs(PPDSC-2517): update TextField component scenarios
  site/pages/components/text-field.tsx
  src/text-field/__tests__/text-field.stories.tsx
Labels: docs, ready for review

#589 docs(PPDSC-2666): caption documentation
  site/pages/components/byline.tsx
  site/pages/components/caption.mdx
  site/pages/components/caption.tsx
  site/pages/components/slider.tsx
  site/public/static/illustrations/components/caption-illustration.svg
  site/public/static/illustrations/components/caption/anatomy/anatomy.svg
  site/public/static/illustrations/components/caption/options/credit-text.svg
  site/public/static/illustrations/components/caption/options/inset-spacing.svg
  site/public/static/illustrations/components/caption/usage/inside-images.svg
Labels: docs, ready for review

#588 chore(PPDSC-2611): fewer tests for baseline updates
  .circleci/config.yml
  jest.config.js
  percy-storybook.config.json
  percy.config.js
  scripts/__tests__/check-baseline-updates.test.js
  scripts/check-baseline-updates.js
  scripts/jest.config.js
Labels: ready for review

#584 feat(PPDSC-2694): extend text crop to support rem
  src/utils/__tests__/text-crop.test.ts
  src/utils/__tests__/typography-preset.test.tsx
  src/utils/text-crop.ts
Labels: ready for review, feature

#598 Docs/ppdsc 2550 content update actions and inputs
  site/pages/components/radio-button.tsx
  site/pages/components/select.tsx
  site/pages/components/share-bar.tsx
  site/pages/components/switch.tsx
  site/pages/components/text-field.tsx
Labels: docs
