Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-05, with the labels that each got.

#835 chore(834): cypress upgrade
  .circleci/config.yml
  Makefile
  package.json
  yarn.lock
Labels: ready for review

#863 ci(798): move build icons into install deps
  .circleci/config.yml
Labels: ready for review

#848 Docs(722) - Slider component storybook scenarios
  src/slider/__tests__/slider.stories.tsx
Labels: docs, ready for review

#864 fix(795): automated a11y tests fails on website homepage
  cypress/site/percy/fullpage-snapshots.cy.js
  scripts/generate-a11y-tests-web.ts
  site/components/homepage/hero/hero-interactive-elements.tsx
  site/components/homepage/whats-new/whats-new.tsx
Labels: fix, ready for review

#882 docs(720): add progress indicator story
  src/icons/__tests__/progress-indicator.stories.tsx
Labels: docs

#879 docs(812): add accessibility statement to docs site
  site/components/page-introduction/page-introduction.tsx
  site/components/page-introduction/types.ts
  site/components/site-footer.tsx
  site/pages/help/accessibility-statement.tsx
  site/pages/help/terms-and-conditions.tsx
  site/utils/colors-token-description.tsx
Labels: docs, ready for review

#885 chore(871): snapshot test package.json
  package.json
  scripts/build-package-json-support.js
  scripts/build-package-json.js
  src/__tests__/__snapshots__/package.test.ts.snap
  src/__tests__/package.test.ts
Labels: ready for review

#888 chore(824): run percy in parallel
  .circleci/config.yml
Labels: ready for review

#872 Fix/821 pagination spacing using columnGap
  site/pages/components/pagination.tsx
  src/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
  src/pagination/components/items/pagination-items.tsx
  src/pagination/components/list-item/list-item.tsx
  src/pagination/defaults.ts
  src/pagination/pagination.tsx
  src/pagination/styled.tsx
  src/pagination/types.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: fix, ready for review

#881 docs(723): Standfirst Storybook Enhancement
  src/standfirst/__tests__/standfirst.stories.tsx
Labels: docs, ready for review

#890 chore(843): percy flaky tests
  .storybook/preview.js
  src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
  src/card-composable/__tests__/__stories/card-composable.stories.tsx
  src/utils/audio-tests.tsx
  src/video-player/__tests__/video-player.stories.tsx
Labels: ready for review

#893 chore(843): remove empty include option in skip-percy-tests
  .storybook/preview.js
Labels: ready for review

#849 docs(811): add font metrics calculator to theme docs
  package.json
  scripts/build-package-json-support.js
  site/components/text-crop-calculator/@types/detect-font.d.ts
  site/components/text-crop-calculator/app-state-context.tsx
  site/components/text-crop-calculator/components/config.ts
  site/components/text-crop-calculator/components/edit-metrics.tsx
  site/components/text-crop-calculator/components/font-selector/file-upload-selector.tsx
  site/components/text-crop-calculator/components/font-selector/font-injector.tsx
  site/components/text-crop-calculator/components/font-selector/google-font-selector.tsx
  site/components/text-crop-calculator/components/font-selector/index.tsx
  site/components/text-crop-calculator/components/font-selector/system-font-selector.tsx
  site/components/text-crop-calculator/components/font-selector/url-font-selector.tsx
  site/components/text-crop-calculator/components/metric.tsx
  site/components/text-crop-calculator/components/metrics-preview.tsx
  site/components/text-crop-calculator/components/output-css.tsx
  site/components/text-crop-calculator/components/styled.tsx
  site/components/text-crop-calculator/json/google-font-api.json
  site/components/text-crop-calculator/json/system-fonts.json
  site/components/text-crop-calculator/text-crop-calculator.tsx
  site/components/text-crop-calculator/unpack.ts
  site/pages/theme/theming/creating-a-theme.mdx
  site/pages/theme/theming/creating-a-theme.tsx
  site/public/static/examples/theming/__extends_1.tsx
  site/public/static/examples/theming/__extends_2.tsx
  yarn.lock
Labels: docs, ready for review

#876 Docs(822) Card Composable doc site
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/card-composable.tsx
  site/public/static/illustrations/components/card-composable/anatomy.svg
  site/public/static/illustrations/components/card-composable/behaviours/grid-layout.svg
  site/public/static/illustrations/components/card-composable/behaviours/static.svg
  site/public/static/illustrations/components/card-composable/hero.svg
  site/public/static/illustrations/components/card-composable/options/expand.svg
  site/public/static/illustrations/components/card-composable/options/inset.svg
  site/public/static/illustrations/components/card-composable/options/order.svg
  site/public/static/illustrations/components/card-composable/options/span.svg
  site/public/static/illustrations/components/card-composable/usage/do-1.svg
  site/public/static/illustrations/components/card-composable/usage/do-2.svg
  site/public/static/illustrations/components/card-composable/usage/do-3.svg
  site/public/static/illustrations/components/card-composable/usage/dont-1.svg
  site/public/static/illustrations/components/card-composable/usage/dont-2.svg
  site/routes.ts
Labels: docs, ready for review

#878 docs(852): add composed section and slices
  .storybook/preview.js
  src/card-composable/__tests__/card-composable.stories.tsx
  src/card-composable/__tests__/the-sun-cards.tsx
  src/card-composable/__tests__/the-times-cards.tsx
  src/form/__tests__/form.stories.tsx
  src/stories/form.stories.tsx
  src/stories/slices.stories.tsx
Labels: docs, ready for review
