Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-06, with the labels that each got.

#895 feat(TMR-1134): refactor form input logic
  src/form/__tests__/form.test.tsx
  src/form/form-entry.tsx
  src/form/form-input.tsx
  src/text-field/types.ts
Labels: feature

#897 fix(896): fix package.json test when bump version
  src/__tests__/__snapshots__/package.test.ts.snap
  src/__tests__/package.test.ts
Labels: fix

#901 docs(900): fix typography docs
  site/pages/theme/presets/typography-presets.tsx
Labels: docs

#899 feat(898): Select panel position
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/select/__tests__/select.stories.tsx
  src/select/__tests__/select.test.tsx
  src/select/select.tsx
  src/select/types.ts
Labels: feature
