Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-04, with the labels that each got.

#781 docs(719): text cropping storybook
  .storybook/preview.js
  src/typography/__tests__/presets-cropping.stories.tsx
  src/typography/__tests__/text-cropping.stories.tsx
Labels: docs, ready for review

#785 docs(741): update radio-group stories
  src/radio-button/__tests__/helpers.tsx
  src/radio-button/__tests__/radio-button.stories.tsx
Labels: docs, ready for review

#797 docs(742): link stories
  site/pages/components/link.tsx
  src/link/__tests__/link.stories.tsx
Labels: docs, ready for review

#789 docs(743): update tag component scenarios - storybook
  src/tabs/__tests__/tabs.stories.tsx
  src/tag/__tests__/tag.stories.tsx
Labels: docs, ready for review

#800 Build/782 parallel cypress webpack 5
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .storybook/main.js
  Makefile
  README.md
  cypress/site/functional/accessibility.common.js
  cypress/site/functional/consent.cy.js
  cypress/support/commands.js
  docs/scripts.md
  docs/testing.md
  multi-reporter-config.json
  package.json
  scripts/generate-a11y-tests-comps.js
  scripts/generate-a11y-tests-web.ts
  scripts/generate-icons/index.js
  site/jest.config.js
  site/next.config.js
  src/jest.config.js
  src/video-player/__tests__/video-player-default.stories.tsx
  webpack.e2e.config.js
  yarn.lock
Labels: ready for review

#801 docs(734): move header above sidebar in html
  site/components/layout.tsx
Labels: docs, ready for review

#813 fix(809): Button alignment mismatching on Custom restore focus - Modal scenario
  src/modal/__tests__/modal.stories.tsx
Labels: fix, ready for review

#790 docs(739): switch story updates
  src/switch/__tests__/helpers.tsx
  src/switch/__tests__/switch.stories.tsx
  src/switch/__tests__/switch.test.tsx
Labels: docs, ready for review

#802 feat:(726) card composable
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/__tests__/__snapshots__/index.test.ts.snap
  src/card-composable/__tests__/__snapshots__/card-composable.test.tsx.snap
  src/card-composable/__tests__/__stories/card-composable.stories.tsx
  src/card-composable/__tests__/card-composable.test.tsx
  src/card-composable/card-composable.tsx
  src/card-composable/context.ts
  src/card-composable/defaults.ts
  src/card-composable/index.ts
  src/card-composable/style-presets.ts
  src/card-composable/styled.tsx
  src/card-composable/types.ts
  src/card/style-presets.ts
  src/grid-layout/__tests__/stories/grid-card.tsx
  src/grid-layout/__tests__/stories/grid-layout.stories.tsx
  src/index.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/presets/style-presets.ts
Labels: ready for review, feature, breaking change, dependencies

#807 docs(721): update select component scenarios - storybook
  .gitignore
  scripts/generate-icons/used-icons-list.json
  src/breadcrumbs/__tests__/breadcrumbs.stories.tsx
  src/pagination/__tests__/pagination.stories.tsx
  src/select/__tests__/select.stories.tsx
Labels: docs, ready for review

#819 docs(746): hide e2e tests from storybook
  .storybook/manager-head.html
  cypress/components/audio-player-composable.cy.js
  cypress/components/auto-play-audio-player.cy.js
  cypress/components/drawer.cy.js
  cypress/components/image.cy.js
  src/audio-player-composable/__tests__/audio-player-composable-e2e.stories.tsx
  src/audio-player/__tests__/auto-play-audio-player.stories.tsx
  src/drawer/__tests__/drawer-e2e.stories.tsx
  src/image/__tests__/image-e2e.stories.tsx
  src/test/percy-skip.stories.tsx
Labels: docs, ready for review

#830 docs(730): update video player component scenarios storybook
  package.json
  site/pages/components/video-player.tsx
  src/card-composable/__tests__/__stories/card-composable.stories.tsx
  src/test/storybook-comps.tsx
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/video-player/__tests__/config.ts
  src/video-player/__tests__/video-player-default.stories.tsx
  src/video-player/__tests__/video-player-overrides.stories.tsx
  src/video-player/__tests__/video-player.stories.tsx
  src/video-player/__tests__/video-player.test.tsx
  src/video-player/defaults.ts
  src/video-player/types.ts
Labels: docs, ready for review

#838 feat(751): add optimisation to with-own-theme
  site/pages/_app.tsx
  src/newskit-provider/__tests__/__snapshots__/newskitprovider.test.tsx.snap
  src/newskit-provider/__tests__/newskitprovider.test.tsx
  src/newskit-provider/context.tsx
  src/newskit-provider/newskit-provider.tsx
  src/test/__tests__/test-utils.test.ts
  src/theme/emotion.tsx
  src/utils/with-own-theme.tsx
Labels: ready for review, feature

#718 feat(PPDSC-2859): use newskit-website theme from publisher
  package.json
  site/components/__tests__/__snapshots__/enum-table.test.tsx.snap
  site/components/__tests__/__snapshots__/site-header.test.tsx.snap
  site/components/base-card/__tests__/__snapshots__/base-card.test.tsx.snap
  site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap
  site/components/content-structure/__tests__/__snapshots__/content-structure.test.tsx.snap
  site/components/flags/mono-keyboard/__tests__/__snapshots__/mono-keyboard.test.tsx.snap
  site/components/header-index/__tests__/__snapshots__/header-index.test.tsx.snap
  site/components/icons/__tests__/__snapshots__/icons.test.tsx.snap
  site/components/legacy-block/__tests__/__snapshots__/legacyblock.test.tsx.snap
  site/components/logo/__tests__/__snapshots__/logo.test.tsx.snap
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/meta/__tests__/__snapshots__/meta.test.tsx.snap
  site/components/page-introduction/__tests__/__snapshots__/page-introduction.test.tsx.snap
  site/components/search/__tests__/__snapshots__/new-start-screen.test.ts.snap
  site/components/search/__tests__/__snapshots__/search.test.ts.snap
  site/components/search/new-start-screen.tsx
  site/components/search/search.tsx
  site/components/section-introduction/__tests__/__snapshots__/section-introduction.test.ts.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/site-footer.tsx
  site/components/step/__tests__/__snapshots__/step.test.tsx.snap
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/components/svg-previewer/colors-theme-list.tsx
  site/components/table-of-contents/__tests__/__snapshots__/table-of-contents.test.tsx.snap
  site/components/table/__tests__/__snapshots__/table.test.tsx.snap
  site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap
  site/components/text-section/__tests__/__snapshots__/content-text.test.ts.snap
  site/components/unpack-content/__tests__/__snapshots__/unpack-content.test.tsx.snap
  site/components/usage-card/__tests__/__snapshots__/usage-card.test.tsx.snap
  site/templates/foundation-page-template/__tests__/__snapshots__/foundation-page-template.test.tsx.snap
  site/templates/guide-page-template/guide-page-template.tsx
  site/templates/pattern-page-template/__tests__/__snapshots__/pattern-page-template.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/accessibility-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/anatomy-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/behaviors-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/code-examples-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/common-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/compliance-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/interactive-demo-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/options-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/related-components-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/seo-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/states-section.test.tsx.snap
  site/templates/template-sections/__tests__/__snapshots__/usage-section.test.tsx.snap
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  site/theme/__tests__/doc-theme.test.ts
  site/theme/colors-dark.json
  site/theme/colors-light.json
  site/theme/doc-theme.ts
  site/theme/fonts.json
  site/theme/overlays-dark.json
  site/theme/overlays.json
  site/theme/style-presets.ts
  site/theme/typography-presets.json
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  yarn.lock
Labels: ready for review, feature

#839 fix(732): fix inline drawer behaviour
  site/components/sidebar/__tests__/sidebar.test.tsx
  src/dialog/base-dialog-function.tsx
  src/dialog/base-dialog-view.tsx
  src/dialog/types.ts
  src/drawer/__tests__/drawer.stories.tsx
  src/drawer/__tests__/transitions/focus-on-entered.test.tsx
  src/drawer/__tests__/transitions/no-focus-on-entering.test.tsx
  src/drawer/drawer.tsx
Labels: fix, ready for review

#841 ci(834): use circle CI test splitting for cypress
  .circleci/config.yml
  package.json
  yarn.lock
Labels: ready for review

#820 docs(728) - Toast component update scenarios - storybook
  cypress/components/toast.cy.js
  src/toast/__tests__/toast-e2e.stories.tsx
  src/toast/__tests__/toast.stories.tsx
Labels: docs, ready for review

#850 ci(727): upgrade axe-core
  package.json
  src/selection-list/__tests__/__snapshots__/selection-list.test.tsx.snap
  src/selection-list/selection-list-option.tsx
  yarn.lock
Labels: ready for review

#847 chore(805): nx and rspack on existing project structure
  .circleci/config.yml
  .eslintrc.base.json
  .eslintrc.js
  .eslintrc.json
  .storybook/addons/tealium/register.js
  .storybook/manager.js
  .storybook/preview.js
  Makefile
  docs/scripts.md
  jest.config.js
  jest.preset.js
  nx.json
  package.json
  rspack.config.js
  scripts/templates-integration-test/cypress.config.js
  site/.eslintrc.json
  site/jest.config.js
  site/pages/getting-started/code/testing.mdx
  site/project.json
  site/tsconfig.spec.json
  src/.babelrc
  src/.eslintrc.json
  src/jest.config.js
  src/project.json
  src/test/__tests__/test-utils.test.ts
  src/tsconfig.spec.json
  tsconfig.common.json
  tsconfig.eslint.json
  yarn.lock
Labels: ready for review
