Repository newscorp-ghfb/NewsKit, pull requests merged in 2023-03, with the labels that each got.

#662 docs(PPDSC-2811): update screen-reader-only scenarios
  src/screen-reader-only/__tests__/screen-reader-only.stories.tsx
Labels: docs, ready for review

#673 docs(PPDSC-2819): update StructuredList component storybook scenarios
  src/structured-list/__tests__/structured-list.stories.tsx
Labels: docs, ready for review

#670 docs(PPDSC-2796): video player documentation
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/video-player.tsx
  site/public/static/illustrations/components/video-player/anatomy.svg
  site/public/static/illustrations/components/video-player/default-player.svg
  site/public/static/illustrations/components/video-player/hero.svg
  site/public/static/illustrations/components/video-player/player-in-card.svg
  site/routes.ts
Labels: docs, ready for review

#667 docs(PPDSC-2812): update scroll stories
  cypress/components/scroll.cy.js
  site/templates/foundation-page-template/__tests__/__snapshots__/foundation-page-template.test.tsx.snap
  site/templates/pattern-page-template/__tests__/__snapshots__/pattern-page-template.test.tsx.snap
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/scroll/__tests__/scroll.stories.tsx
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/overlays.ts
  src/theme/newskit-dark.ts
  src/video-player/__tests__/__snapshots__/video-player.test.tsx.snap
Labels: docs, ready for review, ready for design review

#653 feat(PPDSC-2798): expose css variables
  lib/codemod/README.md
  site/components/theme-provider-site/index.ts
  site/components/theme-provider-site/theme-provider-site.tsx
  site/pages/_app.tsx
  site/pages/patterns/overview.tsx
  site/pages/theme/overview.tsx
  site/pages/theme/theming/using-a-theme.mdx
  site/templates/foundation-page-template/__tests__/__snapshots__/foundation-page-template.test.tsx.snap
  site/templates/foundation-page-template/foundation-page-template.tsx
  site/templates/guide-page-template/guide-page-template.tsx
  site/templates/pattern-page-template/__tests__/__snapshots__/pattern-page-template.test.tsx.snap
  site/templates/pattern-page-template/pattern-page-template.tsx
  src/newskit-provider/__tests__/__snapshots__/newskitprovider.test.tsx.snap
  src/newskit-provider/__tests__/newskitprovider.test.tsx
  src/newskit-provider/newskit-provider.tsx
  src/theme/__tests__/__snapshots__/theme-provider.test.tsx.snap
  src/theme/__tests__/theme-provider.test.tsx
  src/theme/css-variables.tsx
  src/theme/emotion.tsx
Labels: ready for review, feature

#664 docs(PPDSC-2705): update grid storybook scenarios
  .storybook/preview.js
  src/grid/__tests__/grid.stories.tsx
Labels: docs, ready for review

#633 Docs/ppdsc 2562 content updates miscellaneous
  site/pages/components/overview.tsx
  site/pages/theme/foundation/colours.tsx
  site/pages/theme/overview.tsx
  site/routes.ts
  site/utils/colors-token-description.tsx
Labels: docs, ready for review

#674 docs(PPDSC-2825): update UnorderedList component storybook scenarios
  scripts/generate-icons/used-icons-list.json
  src/unordered-list/__tests__/unordered-list.stories.tsx
Labels: docs, ready for review

#680 Fix/ppdsc 2854 flaky tests
  scripts/percy_local.sh
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  yarn.lock
Labels: fix

#666 docs(PPDSC-2816)update-stack-child-component-storybook-scenarios
  src/stack-child/__tests__/stack-child.stories.tsx
Labels: docs, ready for review

#668 docs(PPDSC-2827): update scenarios
  package.json
  scripts/percy_local.sh
  site/pages/components/overview.tsx
  site/pages/components/visibility.tsx
  site/pages/theme/foundation/colours.tsx
  site/pages/theme/overview.tsx
  site/routes.ts
  site/utils/colors-token-description.tsx
  src/audio-player-composable/__tests__/audio-player-composable.test.tsx
  src/audio-player-composable/audio-player-composable.tsx
  src/grid/__tests__/visibility.stories.tsx
  yarn.lock
Labels: docs, ready for review

#676 chore(PPDSC-2848): remove ecr and python in circleci config
  .circleci/config.yml
Labels: ready for review

#681 docs(PPDSC-2845): update image playground
  site/pages/components/image.tsx
Labels: docs, ready for review

#684 docs(PPDSC-2800) inline-message-comp-update
  src/inline-message/__tests__/inline-message.stories.tsx
Labels: enhancement, ready for review

#682 docs(PPDSC-2708): update IconButton component storybook scenarios
  src/icon-button/__tests__/icon-button.stories.tsx
Labels: docs, ready for review, Waiting for Percy

#689 Docs/ppdsc 2851 media query hooks message
  site/components/code-highlighter-theme.ts
  site/pages/components/utils/hooks.mdx
  site/templates/template-sections/__tests__/__snapshots__/code-examples-section.test.tsx.snap
Labels: docs, ready for review

#687 docs/PPDSC-2802: layer scenarios
  site/pages/components/layer.tsx
  src/layer/__tests__/layer.stories.tsx
Labels: docs, Waiting for Percy

#693 feat(ISSUE-4): add fullWidthSingleCell prop to structuredListCell
  site/pages/components/structured-list.tsx
  src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap
  src/structured-list/__tests__/structured-list.stories.tsx
  src/structured-list/__tests__/structured-list.test.tsx
  src/structured-list/structured-list-item.tsx
  src/structured-list/types.ts
Labels: fix, ready for review

#678 docs(PPDSC-2649): add patterns solutions section
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/components/sidebar/sidebar-navigation.tsx
  site/pages/patterns/overview.tsx
  site/pages/patterns/solutions/account.tsx
  site/pages/patterns/solutions/help-hub.tsx
  site/public/static/illustrations/patterns/solutions/account/01-hero.svg
  site/public/static/illustrations/patterns/solutions/account/02-profile.svg
  site/public/static/illustrations/patterns/solutions/account/03-subs-billing.svg
  site/public/static/illustrations/patterns/solutions/account/04-holiday-stops.svg
  site/public/static/illustrations/patterns/solutions/account/05-delivery.svg
  site/public/static/illustrations/patterns/solutions/account/06-newsletters.svg
  site/public/static/illustrations/patterns/solutions/help-hub/01-hero.svg
  site/public/static/illustrations/patterns/solutions/help-hub/02-most-read.svg
  site/public/static/illustrations/patterns/solutions/help-hub/03-search.svg
  site/public/static/illustrations/patterns/solutions/help-hub/04-branding.svg
  site/public/static/illustrations/patterns/solutions/help-hub/05-algolia.svg
  site/routes.ts
Labels: docs, ready for review

#672 feat(PPDSC-2786): pagination component
  scripts/generate-icons/used-icons-list.json
  src/__tests__/__snapshots__/index.test.ts.snap
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  src/breadcrumbs/breadcrumbs.tsx
  src/index.ts
  src/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
  src/pagination/__tests__/pagination.stories.tsx
  src/pagination/__tests__/pagination.test.tsx
  src/pagination/__tests__/utils.test.ts
  src/pagination/components/first-item/first-item.tsx
  src/pagination/components/first-item/index.ts
  src/pagination/components/first-item/types.ts
  src/pagination/components/item/index.ts
  src/pagination/components/item/pagination-item.tsx
  src/pagination/components/items/index.ts
  src/pagination/components/items/pagination-items.tsx
  src/pagination/components/last-item/index.ts
  src/pagination/components/last-item/last-item.tsx
  src/pagination/components/last-item/types.ts
  src/pagination/components/next-item/index.ts
  src/pagination/components/next-item/next-item.tsx
  src/pagination/components/next-item/types.ts
  src/pagination/components/prev-item/index.ts
  src/pagination/components/prev-item/prev-item.tsx
  src/pagination/components/prev-item/types.ts
  src/pagination/components/types.ts
  src/pagination/context.tsx
  src/pagination/defaults.ts
  src/pagination/index.ts
  src/pagination/pagination.tsx
  src/pagination/style-presets.ts
  src/pagination/styled.tsx
  src/pagination/types.ts
  src/pagination/utils.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#688 docs(PPDSC-2803): new menu scenarios
  site/pages/components/menu.tsx
  src/menu/__tests__/menu.stories.tsx
Labels: docs, ready for review

#694 docs(PPDSC-2855) pagination documentation
  site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  site/pages/components/pagination.tsx
  site/public/static/illustrations/components/pagination/anatomy.svg
  site/public/static/illustrations/components/pagination/hero.svg
  site/public/static/illustrations/components/pagination/options/boundaries.svg
  site/public/static/illustrations/components/pagination/options/firstlast.svg
  site/public/static/illustrations/components/pagination/options/siblings.svg
  site/public/static/illustrations/components/pagination/options/size.svg
  site/public/static/illustrations/components/pagination/options/truncation.svg
  site/public/static/illustrations/components/pagination/states/active.svg
  site/public/static/illustrations/components/pagination/states/base.svg
  site/public/static/illustrations/components/pagination/states/disabled.svg
  site/public/static/illustrations/components/pagination/states/focus.svg
  site/public/static/illustrations/components/pagination/states/hover.svg
  site/public/static/illustrations/components/pagination/states/selected.svg
  site/public/static/illustrations/components/pagination/usage/do-01.svg
  site/public/static/illustrations/components/pagination/usage/do-02.svg
  site/public/static/illustrations/components/pagination/usage/do-03.svg
  site/routes.ts
Labels: docs

#691 fix(PPDSC-2847): focus outlines
  lib/codemod/jest.config.js
  site/components/base-card/__tests__/__snapshots__/base-card.test.tsx.snap
  site/components/feature-card/__tests__/__snapshots__/feature-card.test.tsx.snap
  site/components/media-list/__tests__/__snapshots__/media-list.test.tsx.snap
  site/components/usage-card/__tests__/__snapshots__/usage-card.test.tsx.snap
  site/jest.config.js
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  src/breadcrumbs/style-presets.ts
  src/card/__tests__/__snapshots__/card.test.tsx.snap
  src/card/card.tsx
  src/card/defaults.ts
  src/card/style-presets.ts
  src/card/styled.tsx
  src/jest.config.js
  src/menu/__tests__/__snapshots__/menu.test.tsx.snap
  src/menu/style-presets.ts
  src/popover/__tests__/__snapshots__/popover.test.tsx.snap
  src/popover/style-presets.ts
  src/select/__tests__/__snapshots__/select.test.tsx.snap
  src/selection-list/__tests__/__snapshots__/selection-list.test.tsx.snap
  src/tabs/style-presets.ts
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/outlines.ts
  src/theme/presets/style-presets.ts
  src/utils/recurse-unknown.ts
Labels: fix, ready for review

#695 Docs/ppdsc 2808 popover stories
  .storybook/preview.js
  site/pages/components/popover.tsx
  src/base-floating-element/base-floating-element.tsx
  src/popover/__tests__/popover.stories.tsx
  src/test/test-utils.tsx
Labels: docs, ready for review

#710 fix(SCS-70): structured-list with divider a11y issue
  src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap
  src/structured-list/structured-list.tsx
Labels: fix, ready for review

#696 Feat/ppdsc 2806 update outline utility scenario
  src/theme/foundations/__tests__/outline.stories.tsx
Labels: ready for review, feature

#707 feat(PPDSC-2839): pagination support for custom components
  src/__tests__/__snapshots__/index.test.ts.snap
  src/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
  src/pagination/__tests__/pagination.stories.tsx
  src/pagination/__tests__/pagination.test.tsx
  src/pagination/__tests__/utils.test.ts
  src/pagination/components/button/index.ts
  src/pagination/components/button/pagination-button.tsx
  src/pagination/components/first-item/first-item.tsx
  src/pagination/components/item/pagination-item.tsx
  src/pagination/components/items/pagination-items.tsx
  src/pagination/components/last-item/last-item.tsx
  src/pagination/components/list-item/index.ts
  src/pagination/components/list-item/list-item.tsx
  src/pagination/components/next-item/next-item.tsx
  src/pagination/components/prev-item/prev-item.tsx
  src/pagination/defaults.ts
  src/pagination/index.ts
  src/pagination/pagination.tsx
  src/pagination/styled.tsx
  src/pagination/types.ts
  src/pagination/utils.ts
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
Labels: ready for review, feature

#715 docs(PPDSC-2872): pagination documentation for defaults & customisations
  site/components/component-api/common-logical-props.tsx
  site/components/component-api/component-api.tsx
  site/pages/components/pagination.tsx
Labels: docs, ready for review

#692 Docs/ppdsc 2707 update headline component storybook scenarios
  site/pages/components/headline.tsx
  src/headline/__tests__/headline.stories.tsx
Labels: docs, ready for review

#713 docs(PPDSC-2692): update date-time stories
  site/pages/components/date-time.tsx
  src/date-time/__tests__/date-time.stories.tsx
Labels: docs, ready for review

#714 docs(PPDSC-2704): update stories
  .storybook/preview.js
  scripts/generate-icons/used-icons-list.json
  src/form/__tests__/form-input.stories.tsx
Labels: docs, ready for review

#716 docs(PPDSC-2690): update drawer storybook
  src/drawer/__tests__/drawer-layouts.stories.tsx
  src/drawer/__tests__/drawer.stories.tsx
Labels: docs, ready for review

#461 docs(PPDSC-2477): remove sourcepoint component
  .storybook/addons/tealium/register.js
  site/components/site-footer.tsx
  site/pages/_document.tsx
  site/pages/help/terms-and-conditions.tsx
Labels: docs, ready for review

#776 chore(775): move to GitHub issues
  .github/ISSUE_TEMPLATE/a11y_investigation.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/story.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  githooks/commitmsg.js
  githooks/constants.js
  githooks/preparecommitmsg.js
Labels: ready for review

#711 Docs/ppdsc 2514 checkbox component scenario
  src/checkbox/__tests__/checkbox.stories.tsx
Labels: enhancement, ready for review

#697 docs:(PPDSC-2709) update icons scenarios in storybook
  site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
  site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap
  src/icons/__tests__/__snapshots__/custom-icons.test.tsx.snap
  src/icons/__tests__/icons.stories.tsx
  src/icons/filled/custom/icon-filled-figma.tsx
  src/icons/filled/custom/index.ts
  src/newskit-provider/__tests__/__snapshots__/newskitprovider.test.tsx.snap
  src/theme/__tests__/__snapshots__/creator.test.ts.snap
  src/theme/__tests__/__snapshots__/theme-provider.test.tsx.snap
  src/theme/__tests__/__snapshots__/theme.test.ts.snap
  src/theme/compiler/__tests__/__snapshots__/index.test.ts.snap
  src/theme/foundations/colors.ts
  yarn.lock
Labels: docs, ready for review

#738 docs(PPDSC-2702): updated fieldset stories
  e2e/tests.tsx
  src/assistive-text/assistive-text.tsx
  src/fieldset/__tests__/fieldset.stories.tsx
  src/test/theme-select-object.ts
Labels: docs, ready for review

#768 docs(PPDSC-2703): update form stories
  site/pages/components/form.tsx
  src/form/__tests__/form-input.stories.tsx
  src/form/__tests__/form.stories.tsx
Labels: docs, ready for review
